
// Harness driver for pinned reduction sample kernels (generated by reduction_runner.py).
// Owns main(), deterministic inputs, launch geometry, single-pass dispatch, host
// completion of per-block partials (--cpufinal mode), and result dump. Compute kernels
// and the reduce<>() dispatcher are linked from the pinned, byte-unmodified objects.
//
// Optional energy-measurement mode (--repeat/--graph-batch/--trace-dir, all three
// required together): captures graph_batch launches into one CUDA graph and replays
// it, mirroring Task B's fixtures and Task C's Python-callable runners' torch.cuda.
// CUDAGraph path (M311) -- a plain host-enqueue loop was found to spend 53-87% of its
// window on launch submission for microbenchmark-scale kernels (M310). The pinned
// reduce<T>() dispatcher (reduction.h) takes no stream argument and always launches on
// the default stream. CUDA does not allow capturing the LEGACY default stream (first GPU
// run, M319: beginning capture on stream 0 -> "operation not permitted when stream is
// capturing"), so build_binary() compiles every object with --default-stream per-thread:
// the same unmodified launches then go to cudaStreamPerThread, which is capturable, and
// capture, replay, remainder launches and timing events all use that one stream.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cuda_runtime.h>

#include "reduction.h"

#define CUDA_CHECK(call) do { cudaError_t s_ = (call); \
    if (s_ != cudaSuccess) { std::fprintf(stderr, "FATAL CUDA %s:%d: %s\n", \
    __FILE__, __LINE__, cudaGetErrorString(s_)); std::exit(2); } } while (0)

static long long monotonic_ns() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000000000LL + ts.tv_nsec;
}

int main(int argc, char **argv) {
    if (argc != 7 && argc != 13) {
        std::fprintf(stderr, "usage: %s <size> <threads> <blocks> <which_kernel> <in.bin> <out.bin> "
                     "[--repeat N --graph-batch B --trace-dir DIR]\n", argv[0]);
        return 2;
    }
    const int size = std::atoi(argv[1]);
    const int threads = std::atoi(argv[2]);
    const int blocks = std::atoi(argv[3]);
    const int which_kernel = std::atoi(argv[4]);
    if (size <= 0 || threads <= 0 || blocks <= 0) {
        std::fprintf(stderr, "FATAL: bad geometry\n"); return 2;
    }
    FILE *fi = std::fopen(argv[5], "rb");
    if (!fi) { std::fprintf(stderr, "FATAL: cannot open input\n"); return 2; }
    float *h_in = (float *)std::malloc((size_t)size * sizeof(float));
    float *h_part = (float *)std::malloc((size_t)blocks * sizeof(float));
    if (!h_in || !h_part) { std::fprintf(stderr, "FATAL: host alloc\n"); return 2; }
    if (std::fread(h_in, sizeof(float), size, fi) != (size_t)size) {
        std::fprintf(stderr, "FATAL: short input read\n"); return 2;
    }
    std::fclose(fi);
    float *d_in, *d_out;
    CUDA_CHECK(cudaMalloc(&d_in, (size_t)size * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, (size_t)blocks * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, (size_t)size * sizeof(float), cudaMemcpyHostToDevice));

    long long repeat = 0, graph_batch = 0;
    const char *trace_dir = nullptr;
    if (argc == 13) {
        if (std::strcmp(argv[7], "--repeat") != 0 || std::strcmp(argv[9], "--graph-batch") != 0 ||
            std::strcmp(argv[11], "--trace-dir") != 0) {
            std::fprintf(stderr, "FATAL: expected --repeat N --graph-batch B --trace-dir DIR\n");
            return 2;
        }
        repeat = std::atoll(argv[8]);
        graph_batch = std::atoll(argv[10]);
        trace_dir = argv[12];
        if (repeat <= 0 || graph_batch <= 0) { std::fprintf(stderr, "FATAL: bad repeat/graph-batch\n"); return 2; }
    }

    if (trace_dir == nullptr) {
        reduce<float>(size, threads, blocks, which_kernel, d_in, d_out);
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaDeviceSynchronize());
    } else {
        cudaGraph_t graph;
        cudaGraphExec_t graph_exec;
        CUDA_CHECK(cudaStreamBeginCapture(cudaStreamPerThread, cudaStreamCaptureModeGlobal));
        for (long long i = 0; i < graph_batch; ++i) {
            reduce<float>(size, threads, blocks, which_kernel, d_in, d_out);
        }
        CUDA_CHECK(cudaStreamEndCapture(cudaStreamPerThread, &graph));
        CUDA_CHECK(cudaGraphInstantiate(&graph_exec, graph, nullptr, nullptr, 0));

        // Replay, the remainder launches and the timing events all use the same per-thread stream
        // so they are ordered by construction (no reliance on legacy-stream implicit sync).
        const cudaStream_t replay_stream = cudaStreamPerThread;
        CUDA_CHECK(cudaGraphLaunch(graph_exec, replay_stream));  // warm-up, discarded
        CUDA_CHECK(cudaStreamSynchronize(replay_stream));

        cudaEvent_t ev_begin, ev_end;
        CUDA_CHECK(cudaEventCreate(&ev_begin));
        CUDA_CHECK(cudaEventCreate(&ev_end));
        const long long full_replays = repeat / graph_batch;
        const long long remainder = repeat % graph_batch;
        const long long host_begin_ns = monotonic_ns();
        CUDA_CHECK(cudaEventRecord(ev_begin, replay_stream));
        for (long long r = 0; r < full_replays; ++r) {
            CUDA_CHECK(cudaGraphLaunch(graph_exec, replay_stream));
        }
        for (long long i = 0; i < remainder; ++i) {
            reduce<float>(size, threads, blocks, which_kernel, d_in, d_out);
        }
        CUDA_CHECK(cudaEventRecord(ev_end, replay_stream));
        CUDA_CHECK(cudaEventSynchronize(ev_end));
        const long long host_end_ns = monotonic_ns();
        float elapsed_ms = 0.0f;
        CUDA_CHECK(cudaEventElapsedTime(&elapsed_ms, ev_begin, ev_end));

        char windows_path[4096];
        std::snprintf(windows_path, sizeof(windows_path), "%s/windows.csv", trace_dir);
        FILE *fw = std::fopen(windows_path, "w");
        if (!fw) { std::fprintf(stderr, "FATAL: cannot open windows.csv\n"); return 2; }
        std::fprintf(fw, "block,launches,host_begin_monotonic_ns,host_end_monotonic_ns,cuda_seconds\n");
        std::fprintf(fw, "1,%lld,%lld,%lld,%.9f\n", repeat, host_begin_ns, host_end_ns,
                     (double)elapsed_ms / 1000.0);
        std::fclose(fw);

        CUDA_CHECK(cudaGraphExecDestroy(graph_exec));
        CUDA_CHECK(cudaGraphDestroy(graph));
    }

    CUDA_CHECK(cudaMemcpy(h_part, d_out, (size_t)blocks * sizeof(float), cudaMemcpyDeviceToHost));
    double total = 0.0;
    for (int i = 0; i < blocks; ++i) total += (double)h_part[i];
    FILE *fo = std::fopen(argv[6], "wb");
    if (!fo) { std::fprintf(stderr, "FATAL: cannot open output\n"); return 2; }
    float total_f = (float)total;
    if (std::fwrite(&total_f, sizeof(float), 1, fo) != 1) {
        std::fprintf(stderr, "FATAL: short output write\n"); return 2;
    }
    std::fclose(fo);
    std::printf("REDUCE_DONE size=%d threads=%d blocks=%d kernel=%d partials=%d\n",
                size, threads, blocks, which_kernel, blocks);
    return 0;
}
