#!/usr/bin/env python3
"""Run the pinned CUDA Samples vectorAdd kernel, when a real CUDA toolchain is present.

The repository deliberately contains no CUDA dependency.  This runner therefore
has a strict two-state contract: source, toolchain and runtime checks either
pass and the actual pinned sample kernel is launched, or the command fails
loudly without downloading, installing, substituting an implementation, or
executing the sample's own time-seeded demo main.

Build model (documented because it is unusual): the pinned ``vectorAdd.cu``
contains both the ``vecAdd`` kernel and the sample ``main``.  The kernel object
is compiled with ``-Dmain=vectorAdd_sample_main_disabled`` (a build flag that
renames the sample entry point; the pinned bytes are never modified), then
linked against our harness driver below, which owns ``main``, deterministic
inputs, the catalog launch geometry, and full-output comparison.  All build
flags are recorded in every result for exact reproduction.
"""
from __future__ import annotations

import argparse
import array
import hashlib
import json
import math
import platform
import random
import subprocess
import sys
import tempfile
from pathlib import Path

import cuda_build_target

ROOT = Path(__file__).resolve().parent
SOURCE_REL = "cpp/0_Introduction/vectorAdd/vectorAdd.cu"
PINNED_REVISION = "5443602d89ed99aede2e4b7bf329daddeadb320e"
PINNED_SHA256 = "e02d4a73913aff50976cd9ed5e54d57349b0361d01f80446ecebcd9c71cfc9ae"
SEED = 20260914
RTOL = 1e-5
ATOL = 1e-6

DRIVER_TEMPLATE = r"""
// Harness driver for the pinned vectorAdd sample kernel (generated by copy_runner.py).
// Owns main(), deterministic inputs, launch geometry, and result dump. The compute
// kernel itself is linked from the pinned, byte-unmodified vectorAdd.cu object.
//
// Optional energy-measurement mode (--repeat/--graph-batch/--trace-dir, all three
// required together): captures graph_batch launches into one CUDA graph on a private
// stream and replays it, mirroring Task B's fixtures and Task C's Python-callable
// runners' torch.cuda.CUDAGraph path (M311) -- a plain host-enqueue loop was found to
// spend 53-87% of its window on launch submission for microbenchmark-scale kernels
// (M310), so this driver captures a graph from the start. With no --repeat, the
// single-shot correctness path below is byte-for-byte unchanged.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cuda_runtime.h>

__global__ void vecAdd(float *A, float *B, float *C, int vectorLength);

#define CUDA_CHECK(call) do { cudaError_t s_ = (call); \
    if (s_ != cudaSuccess) { std::fprintf(stderr, "FATAL CUDA %s:%d: %s\n", \
    __FILE__, __LINE__, cudaGetErrorString(s_)); std::exit(2); } } while (0)

static long long monotonic_ns() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000000000LL + ts.tv_nsec;
}

int main(int argc, char **argv) {
    if (argc != 6 && argc != 12) {
        std::fprintf(stderr, "usage: %s <n> <threads> <x.bin> <y.bin> <out.bin> "
                     "[--repeat N --graph-batch B --trace-dir DIR]\n", argv[0]);
        return 2;
    }
    const int n = std::atoi(argv[1]);
    const int threads = std::atoi(argv[2]);
    if (n <= 0 || threads <= 0) { std::fprintf(stderr, "FATAL: bad geometry\n"); return 2; }
    FILE *fx = std::fopen(argv[3], "rb");
    FILE *fy = std::fopen(argv[4], "rb");
    if (!fx || !fy) { std::fprintf(stderr, "FATAL: cannot open inputs\n"); return 2; }
    float *h_x = (float *)std::malloc((size_t)n * sizeof(float));
    float *h_y = (float *)std::malloc((size_t)n * sizeof(float));
    float *h_o = (float *)std::malloc((size_t)n * sizeof(float));
    if (!h_x || !h_y || !h_o) { std::fprintf(stderr, "FATAL: host alloc\n"); return 2; }
    if (std::fread(h_x, sizeof(float), n, fx) != (size_t)n ||
        std::fread(h_y, sizeof(float), n, fy) != (size_t)n) {
        std::fprintf(stderr, "FATAL: short input read\n"); return 2;
    }
    std::fclose(fx); std::fclose(fy);
    float *d_x, *d_y, *d_o;
    CUDA_CHECK(cudaMalloc(&d_x, (size_t)n * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_y, (size_t)n * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_o, (size_t)n * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_x, h_x, (size_t)n * sizeof(float), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_y, h_y, (size_t)n * sizeof(float), cudaMemcpyHostToDevice));
    const int blocks = (n + threads - 1) / threads;

    long long repeat = 0, graph_batch = 0;
    const char *trace_dir = nullptr;
    if (argc == 12) {
        if (std::strcmp(argv[6], "--repeat") != 0 || std::strcmp(argv[8], "--graph-batch") != 0 ||
            std::strcmp(argv[10], "--trace-dir") != 0) {
            std::fprintf(stderr, "FATAL: expected --repeat N --graph-batch B --trace-dir DIR\n");
            return 2;
        }
        repeat = std::atoll(argv[7]);
        graph_batch = std::atoll(argv[9]);
        trace_dir = argv[11];
        if (repeat <= 0 || graph_batch <= 0) { std::fprintf(stderr, "FATAL: bad repeat/graph-batch\n"); return 2; }
    }

    if (trace_dir == nullptr) {
        vecAdd<<<blocks, threads>>>(d_x, d_y, d_o, n);
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaDeviceSynchronize());
    } else {
        cudaStream_t stream;
        CUDA_CHECK(cudaStreamCreate(&stream));
        cudaGraph_t graph;
        cudaGraphExec_t graph_exec;
        CUDA_CHECK(cudaStreamBeginCapture(stream, cudaStreamCaptureModeGlobal));
        for (long long i = 0; i < graph_batch; ++i) {
            vecAdd<<<blocks, threads, 0, stream>>>(d_x, d_y, d_o, n);
        }
        CUDA_CHECK(cudaStreamEndCapture(stream, &graph));
        CUDA_CHECK(cudaGraphInstantiate(&graph_exec, graph, nullptr, nullptr, 0));
        CUDA_CHECK(cudaGraphLaunch(graph_exec, stream));  // warm-up, discarded
        CUDA_CHECK(cudaStreamSynchronize(stream));

        cudaEvent_t ev_begin, ev_end;
        CUDA_CHECK(cudaEventCreate(&ev_begin));
        CUDA_CHECK(cudaEventCreate(&ev_end));
        const long long full_replays = repeat / graph_batch;
        const long long remainder = repeat % graph_batch;
        const long long host_begin_ns = monotonic_ns();
        CUDA_CHECK(cudaEventRecord(ev_begin, stream));
        for (long long r = 0; r < full_replays; ++r) {
            CUDA_CHECK(cudaGraphLaunch(graph_exec, stream));
        }
        for (long long i = 0; i < remainder; ++i) {
            vecAdd<<<blocks, threads, 0, stream>>>(d_x, d_y, d_o, n);
        }
        CUDA_CHECK(cudaEventRecord(ev_end, stream));
        CUDA_CHECK(cudaEventSynchronize(ev_end));
        const long long host_end_ns = monotonic_ns();
        float elapsed_ms = 0.0f;
        CUDA_CHECK(cudaEventElapsedTime(&elapsed_ms, ev_begin, ev_end));

        char windows_path[4096];
        std::snprintf(windows_path, sizeof(windows_path), "%s/windows.csv", trace_dir);
        FILE *fw = std::fopen(windows_path, "w");
        if (!fw) { std::fprintf(stderr, "FATAL: cannot open windows.csv\n"); return 2; }
        std::fprintf(fw, "block,launches,host_begin_monotonic_ns,host_end_monotonic_ns,cuda_seconds\n");
        std::fprintf(fw, "1,%lld,%lld,%lld,%.9f\n", repeat, host_begin_ns, host_end_ns,
                     (double)elapsed_ms / 1000.0);
        std::fclose(fw);

        CUDA_CHECK(cudaGraphExecDestroy(graph_exec));
        CUDA_CHECK(cudaGraphDestroy(graph));
        CUDA_CHECK(cudaStreamDestroy(stream));
    }

    CUDA_CHECK(cudaMemcpy(h_o, d_o, (size_t)n * sizeof(float), cudaMemcpyDeviceToHost));
    FILE *fo = std::fopen(argv[5], "wb");
    if (!fo) { std::fprintf(stderr, "FATAL: cannot open output\n"); return 2; }
    if (std::fwrite(h_o, sizeof(float), n, fo) != (size_t)n) {
        std::fprintf(stderr, "FATAL: short output write\n"); return 2;
    }
    std::fclose(fo);
    std::printf("COPY_DONE n=%d threads=%d blocks=%d\n", n, threads, blocks);
    return 0;
}
"""


class RunnerBlocked(RuntimeError):
    """A required provenance/toolchain/runtime check failed; never silently fall back."""


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def verify_source(source_root: Path) -> tuple[Path, str]:
    """Verify exact Git revision and sample bytes before compiling anything."""
    source_root = source_root.expanduser().resolve()
    source_file = source_root / SOURCE_REL
    if not source_file.is_file():
        raise RunnerBlocked(f"RUNNER_BLOCKED: missing pinned source {source_file}")
    try:
        revision = subprocess.run(
            ["git", "-C", str(source_root), "rev-parse", "HEAD"],
            check=True, capture_output=True, text=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RunnerBlocked("RUNNER_BLOCKED: source_root is not a readable Git checkout") from exc
    if revision != PINNED_REVISION:
        raise RunnerBlocked(f"RUNNER_BLOCKED: expected revision {PINNED_REVISION}, got {revision}")
    actual_hash = sha256_file(source_file)
    if PINNED_SHA256 and actual_hash != PINNED_SHA256:
        raise RunnerBlocked(f"RUNNER_BLOCKED: source SHA-256 mismatch: expected {PINNED_SHA256}, got {actual_hash}")
    return source_file, revision


def find_nvcc() -> str:
    """Locate nvcc and check the build arch against the target GPU (cuda_build_target.py)."""
    nvcc = cuda_build_target.find_nvcc(RunnerBlocked)
    cuda_build_target.assert_live_arch(build_arch(), RunnerBlocked)
    return nvcc


def build_arch() -> str:
    """sm_120 (Blackwell) unless HARNESS_CUDA_ARCH says otherwise."""
    return cuda_build_target.target_arch(RunnerBlocked)


def build_binary(source_root: Path, workdir: Path, nvcc: str) -> Path:
    """Compile pinned kernel object (main renamed away) + harness driver, link."""
    kernel_src = source_root / SOURCE_REL
    driver_src = workdir / "copy_driver.cu"
    driver_src.write_text(DRIVER_TEMPLATE, encoding="utf-8")
    kernel_obj = workdir / "vectorAdd_kernel.o"
    binary = workdir / "copy_harness"
    common_inc = source_root / "Common"
    if not common_inc.is_dir():
        raise RunnerBlocked(f"RUNNER_BLOCKED: missing helper headers at {common_inc}")
    steps = [
        [nvcc, "-O2", f"-arch={build_arch()}", "-Dmain=vectorAdd_sample_main_disabled",
         "-c", str(kernel_src), "-o", str(kernel_obj)],
        [nvcc, "-O2", f"-arch={build_arch()}", str(driver_src), str(kernel_obj),
         "-o", str(binary)],
    ]
    for step in steps:
        proc = subprocess.run(step, capture_output=True, text=True, cwd=str(workdir))
        if proc.returncode != 0:
            raise RunnerBlocked(f"RUNNER_BLOCKED: nvcc failed: {' '.join(step)}\n{proc.stderr[-2000:]}")
    if not binary.is_file():
        raise RunnerBlocked("RUNNER_BLOCKED: harness binary missing after build")
    return binary


def first_mismatch(got: list[float], want: list[float]) -> int | None:
    """Index of the first element violating cell tolerance, or None if all match."""
    if len(got) != len(want) or not all(math.isfinite(v) for v in got):
        return -1
    return next((i for i, (g, w) in enumerate(zip(got, want))
                 if abs(g - w) > ATOL + RTOL * abs(w)), None)


def deterministic_inputs(n: int) -> tuple[array.array, array.array]:
    """Seed-20260914 FP32-range input pair. Single source of truth for inputs."""
    if n <= 0:
        raise RunnerBlocked("RUNNER_BLOCKED: non-positive vector length")
    rng = random.Random(SEED)
    return (array.array("f", (rng.uniform(-1.0, 1.0) for _ in range(n))),
            array.array("f", (rng.uniform(-1.0, 1.0) for _ in range(n))))


def run_candidate(source_root: Path, regime: str, candidate_id: str, workdir: Path) -> dict:
    """Build the harness, launch the pinned kernel, validate every output element."""
    from copy_adapter import cell_descriptor
    from correctness_reference import ref_cuda_samples_vector_add

    source_file, revision = verify_source(source_root)
    actual_hash = sha256_file(source_file)
    if not PINNED_SHA256:
        raise RunnerBlocked(
            "RUNNER_BLOCKED: PINNED_SHA256 is empty -- record the audited hash "
            f"(observed {actual_hash}) in this file before any GPU run")
    descriptor = cell_descriptor(regime, candidate_id)
    nvcc = find_nvcc()
    binary = build_binary(source_root, workdir, nvcc)
    controls = descriptor["build"]["compile_meta"]
    n = int(descriptor["launch"]["runtime_args"][0].split("=")[1])
    threads = int(controls["threads"])
    blocks = int(controls["blocks"])
    x_arr, y_arr = deterministic_inputs(n)
    x_path, y_path, o_path = workdir / "x.bin", workdir / "y.bin", workdir / "o.bin"
    with open(x_path, "wb") as f:
        x_arr.tofile(f)
    with open(y_path, "wb") as f:
        y_arr.tofile(f)
    proc = subprocess.run(
        [str(binary), str(n), str(threads), str(x_path), str(y_path), str(o_path)],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        raise RunnerBlocked(f"RUNNER_BLOCKED: harness run failed: {proc.stderr[-2000:]}")
    out = array.array("f")
    with open(o_path, "rb") as f:
        out.fromfile(f, n)
    if len(out) != n or not all(math.isfinite(v) for v in out):
        raise RunnerBlocked("RUNNER_BLOCKED: output shape/finiteness check failed")
    expected = ref_cuda_samples_vector_add(list(x_arr), list(y_arr))
    bad = first_mismatch(list(out), expected)
    if bad is not None:
        raise RuntimeError(
            f"CORRUPT_OUTPUT_REJECTED: index {bad}: got {out[bad]}, want {expected[bad]}")
    # Status reflects coordinator-accepted GPU validation 2026-09-19 (12/12 cells).
    # Do not revert without coordinator direction.
    result = {
        "status": "compiled_gpu_verified",
        "source_revision": revision,
        "source_sha256": actual_hash,
        "source_path": SOURCE_REL,
        "regime": regime,
        "candidate_id": candidate_id,
        "n_elements": n,
        "controls": {"threads": threads, "blocks": blocks},
        "build": {"nvcc": nvcc, "arch": build_arch(),
                  "defines": ["main=vectorAdd_sample_main_disabled"],
                  "note": "pinned bytes unmodified; sample main renamed at compile time only"},
        "reference": {"elements_checked": n, "rtol": RTOL, "atol": ATOL},
        "runtime": {
            "python": platform.python_version(),
            "device": "cuda (checked at harness build/runner launch)",
        },
    }
    return result


def prepare_binary_energy_context(source_root: Path, regime: str, candidate_id: str, workdir: Path):
    """Build once, return a BinaryEnergyContext for energy_harness/application_energy_harness.py.
    Mirrors run_candidate()'s setup exactly; does not invoke the binary itself."""
    hpc_dir = Path(__file__).resolve().parents[2] / "energy_harness"
    if str(hpc_dir) not in sys.path:
        sys.path.insert(0, str(hpc_dir))
    from application_energy_harness import BinaryEnergyContext

    from copy_adapter import cell_descriptor
    from correctness_reference import ref_cuda_samples_vector_add

    source_file, revision = verify_source(source_root)
    actual_hash = sha256_file(source_file)
    if not PINNED_SHA256:
        raise RunnerBlocked(
            "RUNNER_BLOCKED: PINNED_SHA256 is empty -- record the audited hash "
            f"(observed {actual_hash}) in this file before any GPU run")
    descriptor = cell_descriptor(regime, candidate_id)
    nvcc = find_nvcc()
    binary = build_binary(source_root, workdir, nvcc)
    controls = descriptor["build"]["compile_meta"]
    n = int(descriptor["launch"]["runtime_args"][0].split("=")[1])
    threads = int(controls["threads"])
    blocks = int(controls["blocks"])
    x_arr, y_arr = deterministic_inputs(n)
    x_path, y_path, o_path = workdir / "x.bin", workdir / "y.bin", workdir / "o.bin"
    with open(x_path, "wb") as f:
        x_arr.tofile(f)
    with open(y_path, "wb") as f:
        y_arr.tofile(f)
    expected = ref_cuda_samples_vector_add(list(x_arr), list(y_arr))

    def check():
        out = array.array("f")
        with open(o_path, "rb") as f:
            out.fromfile(f, n)
        if len(out) != n or not all(math.isfinite(v) for v in out):
            return False
        return first_mismatch(list(out), expected) is None

    return BinaryEnergyContext(
        parent_id="final_cuda_samples_copy", regime=regime, candidate_id=candidate_id,
        source_revision=revision, source_sha256=actual_hash, source_path=SOURCE_REL,
        controls={"threads": threads, "blocks": blocks},
        runtime_info={"python": platform.python_version(), "nvcc": nvcc, "arch": build_arch()},
        binary=binary, argv_prefix=[str(n), str(threads), str(x_path), str(y_path), str(o_path)],
        check=check,
    )


def self_test() -> None:
    from copy_adapter import cell_descriptor

    with tempfile.TemporaryDirectory() as temp:
        fixture = Path(temp) / "source.py"
        fixture.write_bytes(b"pinned fixture")
        expected = sha256_file(fixture)
        assert sha256_file(fixture) == expected
        fixture.write_bytes(b"corrupt fixture")
        assert sha256_file(fixture) != expected
    assert "DRIVER_TEMPLATE" in globals() and "vecAdd<<<" in DRIVER_TEMPLATE
    assert "int main(int argc" in DRIVER_TEMPLATE  # driver owns main; sample main renamed at build
    assert "-Dmain=" not in DRIVER_TEMPLATE  # the define lives in build_binary, documented there
    for regime in ("small", "medium", "large"):
        for candidate in ("c1", "c2", "c3", "c4"):
            d = cell_descriptor(regime, candidate)
            assert d["source_status"] == "source_verified"
            assert d["implementation_status"] == "compiled_gpu_verified"
            assert d["semantics"]["same_problem_across_candidates"]
    x, y = deterministic_inputs(1024)
    assert len(x) == len(y) == 1024
    assert list(x) == list(deterministic_inputs(1024)[0])
    from correctness_reference import ref_cuda_samples_vector_add
    expected = ref_cuda_samples_vector_add(list(x), list(y))
    assert len(expected) == 1024
    assert first_mismatch(expected, expected) is None
    corrupt = list(expected); corrupt[11] += 0.25
    assert first_mismatch(corrupt, expected) == 11
    assert first_mismatch(expected[:-1], expected) == -1
    assert first_mismatch([float("nan")] * 1024, expected) == -1
    print("CPU_ONLY_COPY_RUNNER_OK: hash/descriptor/determinism/reference checks passed")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", type=Path)
    parser.add_argument("--regime", choices=("small", "medium", "large"))
    parser.add_argument("--candidate", choices=("c1", "c2", "c3", "c4"))
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--workdir", type=Path, default=None)
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return 0
    if args.source_root is None or args.regime is None or args.candidate is None:
        parser.error("--source-root, --regime, and --candidate are required unless --self-test")
    try:
        with tempfile.TemporaryDirectory(prefix="copy_harness_") as temp:
            workdir = args.workdir or Path(temp)
            workdir.mkdir(parents=True, exist_ok=True)
            print(json.dumps(run_candidate(args.source_root, args.regime, args.candidate, workdir),
                             sort_keys=True))
    except RunnerBlocked as exc:
        print(str(exc), file=sys.stderr)
        return 3
    return 0


if __name__ == "__main__":
    main()
