#!/usr/bin/env python3
"""Run the pinned CUB BlockReduce geometry, when a real CUDA toolchain is present.

The repository deliberately contains no CUDA dependency. This runner therefore
has a strict two-state contract: source, toolchain and runtime checks either
pass and the actual pinned CUB headers execute, or the command fails loudly
without downloading, installing, substituting an implementation, or executing
the pinned file's own Catch2 test main.

Build model (documented because it is unusual): the pinned
``cub/test/catch2_test_block_reduce.cu`` instantiates
``cub::BlockReduce`` inside a Catch2 test binary, which this project does not
build. The test file is hash-verified as the provenance anchor for the exact
instantiation under test; the executed code is our harness driver below (owns
``main``, deterministic inputs, catalog launch geometry, result dump) compiled
against the pinned CUB headers from the same checkout, which are header-only.
All build flags are recorded in every result for exact reproduction.
"""
from __future__ import annotations

import argparse
import array
import hashlib
import json
import math
import platform
import random
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TEST_REL = "cub/test/catch2_test_block_reduce.cu"
BLOCK_REDUCE_REL = "cub/cub/block/block_reduce.cuh"
PINNED_REVISION = "d670cb5242c2b855d0286bb7f4921e85543c177b"
PINNED_TEST_SHA256 = "90f654fa66549f8f31666522d0c8f9c21d60c26a90e94ae62c9ce23b2fc572a6"
SEED = 20260914
RTOL = 1e-5
ATOL = 1e-6

# Catalog candidates c1..c4 map to (BlockDimX, ItemsPerThread); the tile always
# covers exactly the 1024 valid items in one block.
CANDIDATE_GEOMETRY = {"c1": (32, 32), "c2": (64, 16), "c3": (128, 8), "c4": (256, 4)}

DRIVER_TEMPLATE = r"""
// Harness driver for pinned CUB BlockReduce geometry (generated by cub_block_runner.py).
// Owns main(), deterministic inputs, launch geometry, and result dump. The reduction
// itself is cub::BlockReduce instantiated exactly as the pinned catch2 test does,
// compiled against the pinned CUB headers; the Catch2 test binary is never built.
//
// Optional energy-measurement mode (--repeat/--graph-batch/--trace-dir, all three
// required together): captures graph_batch launches into one CUDA graph on a private
// stream and replays it, mirroring Task B's fixtures and Task C's Python-callable
// runners' torch.cuda.CUDAGraph path (M311) -- a plain host-enqueue loop was found to
// spend 53-87% of its window on launch submission for microbenchmark-scale kernels
// (M310), so this driver captures a graph from the start. With no --repeat, the
// single-shot correctness path below is byte-for-byte unchanged.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cuda_runtime.h>

#include <cub/block/block_reduce.cuh>

#ifndef HARNESS_BLOCK_X
#error "HARNESS_BLOCK_X must be supplied at compile time"
#endif
#ifndef HARNESS_ITEMS_PER_THREAD
#error "HARNESS_ITEMS_PER_THREAD must be supplied at compile time"
#endif
#ifndef HARNESS_VALID_ITEMS
#error "HARNESS_VALID_ITEMS must be supplied at compile time"
#endif

#define CUDA_CHECK(call) do { cudaError_t s_ = (call); \
    if (s_ != cudaSuccess) { std::fprintf(stderr, "FATAL CUDA %s:%d: %s\n", \
    __FILE__, __LINE__, cudaGetErrorString(s_)); std::exit(2); } } while (0)

static long long monotonic_ns() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000000000LL + ts.tv_nsec;
}

// Two real bugs found here 2026-09-21, compiling this driver against a real
// checkout for the first time ever (it was always implemented_unvalidated_runtime,
// never GPU-run):
//
// 1. The compile-time defines were originally BLOCK_X/ITEMS_PER_THREAD/VALID_ITEMS.
//    cub's OWN internal headers (cub/util_arch.cuh's RegBoundScaling/MemBoundScaling/
//    NoScaling, and BlockReduce's own Sum()/Reduce() member templates in
//    cub/block/block_reduce.cuh) declare members and template parameters with the
//    exact bare name `ITEMS_PER_THREAD`. The preprocessor does not know about C++
//    scoping, so `-DITEMS_PER_THREAD=32` rewrote those declarations too (e.g.
//    `static constexpr int ITEMS_PER_THREAD = ...` became `static constexpr int
//    32 = ...`), breaking cub's own headers. Renamed to the harness-prefixed
//    HARNESS_BLOCK_X/HARNESS_ITEMS_PER_THREAD/HARNESS_VALID_ITEMS throughout, which
//    do not collide with anything in the pinned CUB headers (verified by compiling
//    against them for real).
// 2. cub::BlockReduce<T, BlockDimX, Algorithm=.., BlockDimY=1, BlockDimZ=1> takes
//    only the data type and the X block dimension as required template arguments
//    (verified against the real pinned header): there is no items-per-thread class
//    template parameter. Items-per-thread is deduced from the array argument by
//    Sum's own member function template, `T Sum(T (&inputs)[ITEMS_PER_THREAD])`
//    (that name lives in cub's own header, not ours). The original code passed
//    items-per-thread as BlockReduce's third template argument (the algorithm enum
//    slot) -- also never compiled.
template <int TBlockX, int TItems>
__global__ void block_reduce_kernel(const float *in, float *out) {
    __shared__ typename cub::BlockReduce<float, TBlockX>::TempStorage temp;
    const int tid = threadIdx.x;
    float thread_data[TItems];
    for (int i = 0; i < TItems; ++i) thread_data[i] = in[tid * TItems + i];
    float aggregate = cub::BlockReduce<float, TBlockX>(temp).Sum(thread_data);
    if (tid == 0) *out = aggregate;
}

int main(int argc, char **argv) {
    if (argc != 4 && argc != 10) {
        std::fprintf(stderr, "usage: %s <valid_items> <in.bin> <out.bin> "
                     "[--repeat N --graph-batch B --trace-dir DIR]\n", argv[0]);
        return 2;
    }
    const int valid_items = std::atoi(argv[1]);
    if (valid_items != HARNESS_VALID_ITEMS) {
        std::fprintf(stderr, "FATAL: valid_items %d != compiled %d\n", valid_items, HARNESS_VALID_ITEMS);
        return 2;
    }
    if (HARNESS_BLOCK_X * HARNESS_ITEMS_PER_THREAD != HARNESS_VALID_ITEMS) {
        std::fprintf(stderr, "FATAL: geometry tile %d != valid items %d\n",
                     HARNESS_BLOCK_X * HARNESS_ITEMS_PER_THREAD, HARNESS_VALID_ITEMS);
        return 2;
    }
    FILE *fi = std::fopen(argv[2], "rb");
    if (!fi) { std::fprintf(stderr, "FATAL: cannot open input\n"); return 2; }
    float *h_in = (float *)std::malloc((size_t)valid_items * sizeof(float));
    if (!h_in) { std::fprintf(stderr, "FATAL: host alloc\n"); return 2; }
    if (std::fread(h_in, sizeof(float), valid_items, fi) != (size_t)valid_items) {
        std::fprintf(stderr, "FATAL: short input read\n"); return 2;
    }
    std::fclose(fi);
    float *d_in, *d_out;
    CUDA_CHECK(cudaMalloc(&d_in, (size_t)valid_items * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, (size_t)valid_items * sizeof(float), cudaMemcpyHostToDevice));

    long long repeat = 0, graph_batch = 0;
    const char *trace_dir = nullptr;
    if (argc == 10) {
        if (std::strcmp(argv[4], "--repeat") != 0 || std::strcmp(argv[6], "--graph-batch") != 0 ||
            std::strcmp(argv[8], "--trace-dir") != 0) {
            std::fprintf(stderr, "FATAL: expected --repeat N --graph-batch B --trace-dir DIR\n");
            return 2;
        }
        repeat = std::atoll(argv[5]);
        graph_batch = std::atoll(argv[7]);
        trace_dir = argv[9];
        if (repeat <= 0 || graph_batch <= 0) { std::fprintf(stderr, "FATAL: bad repeat/graph-batch\n"); return 2; }
    }

    if (trace_dir == nullptr) {
        block_reduce_kernel<HARNESS_BLOCK_X, HARNESS_ITEMS_PER_THREAD><<<1, HARNESS_BLOCK_X>>>(d_in, d_out);
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaDeviceSynchronize());
    } else {
        cudaStream_t stream;
        CUDA_CHECK(cudaStreamCreate(&stream));
        cudaGraph_t graph;
        cudaGraphExec_t graph_exec;
        CUDA_CHECK(cudaStreamBeginCapture(stream, cudaStreamCaptureModeGlobal));
        for (long long i = 0; i < graph_batch; ++i) {
            block_reduce_kernel<HARNESS_BLOCK_X, HARNESS_ITEMS_PER_THREAD><<<1, HARNESS_BLOCK_X, 0, stream>>>(d_in, d_out);
        }
        CUDA_CHECK(cudaStreamEndCapture(stream, &graph));
        CUDA_CHECK(cudaGraphInstantiate(&graph_exec, graph, nullptr, nullptr, 0));
        CUDA_CHECK(cudaGraphLaunch(graph_exec, stream));  // warm-up, discarded
        CUDA_CHECK(cudaStreamSynchronize(stream));

        cudaEvent_t ev_begin, ev_end;
        CUDA_CHECK(cudaEventCreate(&ev_begin));
        CUDA_CHECK(cudaEventCreate(&ev_end));
        const long long full_replays = repeat / graph_batch;
        const long long remainder = repeat % graph_batch;
        const long long host_begin_ns = monotonic_ns();
        CUDA_CHECK(cudaEventRecord(ev_begin, stream));
        for (long long r = 0; r < full_replays; ++r) {
            CUDA_CHECK(cudaGraphLaunch(graph_exec, stream));
        }
        for (long long i = 0; i < remainder; ++i) {
            block_reduce_kernel<HARNESS_BLOCK_X, HARNESS_ITEMS_PER_THREAD><<<1, HARNESS_BLOCK_X, 0, stream>>>(d_in, d_out);
        }
        CUDA_CHECK(cudaEventRecord(ev_end, stream));
        CUDA_CHECK(cudaEventSynchronize(ev_end));
        const long long host_end_ns = monotonic_ns();
        float elapsed_ms = 0.0f;
        CUDA_CHECK(cudaEventElapsedTime(&elapsed_ms, ev_begin, ev_end));

        char windows_path[4096];
        std::snprintf(windows_path, sizeof(windows_path), "%s/windows.csv", trace_dir);
        FILE *fw = std::fopen(windows_path, "w");
        if (!fw) { std::fprintf(stderr, "FATAL: cannot open windows.csv\n"); return 2; }
        std::fprintf(fw, "block,launches,host_begin_monotonic_ns,host_end_monotonic_ns,cuda_seconds\n");
        std::fprintf(fw, "1,%lld,%lld,%lld,%.9f\n", repeat, host_begin_ns, host_end_ns,
                     (double)elapsed_ms / 1000.0);
        std::fclose(fw);

        CUDA_CHECK(cudaGraphExecDestroy(graph_exec));
        CUDA_CHECK(cudaGraphDestroy(graph));
        CUDA_CHECK(cudaStreamDestroy(stream));
    }

    float total = 0.0f;
    CUDA_CHECK(cudaMemcpy(&total, d_out, sizeof(float), cudaMemcpyDeviceToHost));
    FILE *fo = std::fopen(argv[3], "wb");
    if (!fo) { std::fprintf(stderr, "FATAL: cannot open output\n"); return 2; }
    if (std::fwrite(&total, sizeof(float), 1, fo) != 1) {
        std::fprintf(stderr, "FATAL: short output write\n"); return 2;
    }
    std::fclose(fo);
    std::printf("BLOCK_REDUCE_DONE items=%d block_x=%d items_per_thread=%d\n",
                valid_items, HARNESS_BLOCK_X, HARNESS_ITEMS_PER_THREAD);
    return 0;
}
"""


class RunnerBlocked(RuntimeError):
    """A required provenance/toolchain/runtime check failed; never silently fall back."""


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def verify_source(source_root: Path) -> tuple[Path, str]:
    """Verify exact Git revision and pinned CUB bytes before compiling anything."""
    source_root = source_root.expanduser().resolve()
    test_file = source_root / TEST_REL
    header_file = source_root / BLOCK_REDUCE_REL
    for path in (test_file, header_file):
        if not path.is_file():
            raise RunnerBlocked(f"RUNNER_BLOCKED: missing pinned source {path}")
    try:
        revision = subprocess.run(
            ["git", "-C", str(source_root), "rev-parse", "HEAD"],
            check=True, capture_output=True, text=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RunnerBlocked("RUNNER_BLOCKED: source_root is not a readable Git checkout") from exc
    if revision != PINNED_REVISION:
        raise RunnerBlocked(f"RUNNER_BLOCKED: expected revision {PINNED_REVISION}, got {revision}")
    actual_hash = sha256_file(test_file)
    if actual_hash != PINNED_TEST_SHA256:
        raise RunnerBlocked(
            f"RUNNER_BLOCKED: test SHA-256 mismatch: expected {PINNED_TEST_SHA256}, got {actual_hash}")
    return test_file, revision


def find_nvcc() -> str:
    """Locate nvcc without modifying PATH. CUDA 12.8+ required for sm_120."""
    for candidate in ("/usr/local/cuda-13.2/bin/nvcc", "/usr/local/cuda-12.8/bin/nvcc",
                      "/usr/local/cuda/bin/nvcc"):
        if Path(candidate).is_file():
            return candidate
    found = shutil.which("nvcc")
    if found:
        return found
    raise RunnerBlocked("RUNNER_BLOCKED: no nvcc found (need CUDA 12.8+ for sm_120)")


def build_binary(source_root: Path, workdir: Path, nvcc: str, block_x: int, items: int) -> Path:
    """Compile our harness driver against the pinned CUB headers (header-only).

    Fixed 2026-09-21 (never previously exercised against a real checkout --
    same defect as cub_device_runner.py's build_binary, found while compile-
    verifying both against the real pinned CCCL checkout for the first time):
    CCCL's monorepo nests CUB's own tree one level deeper (`cub/cub/block/...`)
    than this check previously looked for, and cub's headers also transitively
    need libcudacxx/thrust headers from CCCL's sibling components.
    """
    cub_component = source_root / "cub"
    if not (cub_component / "cub" / "block" / "block_reduce.cuh").is_file():
        raise RunnerBlocked(f"RUNNER_BLOCKED: CUB headers not found under {cub_component}")
    libcudacxx_include = source_root / "libcudacxx" / "include"
    thrust_include = source_root / "thrust"
    for include_dir in (libcudacxx_include, thrust_include):
        if not include_dir.is_dir():
            raise RunnerBlocked(f"RUNNER_BLOCKED: required CCCL sibling include dir missing: {include_dir}")
    driver_src = workdir / "cub_block_driver.cu"
    driver_src.write_text(DRIVER_TEMPLATE, encoding="utf-8")
    binary = workdir / "cub_block_harness"
    step = [nvcc, "-O2", "-std=c++17", "-arch=sm_120",
            "-I", str(cub_component), "-I", str(libcudacxx_include), "-I", str(thrust_include),
            f"-DHARNESS_BLOCK_X={block_x}", f"-DHARNESS_ITEMS_PER_THREAD={items}", "-DHARNESS_VALID_ITEMS=1024",
            str(driver_src), "-o", str(binary)]
    proc = subprocess.run(step, capture_output=True, text=True, cwd=str(workdir))
    if proc.returncode != 0:
        raise RunnerBlocked(f"RUNNER_BLOCKED: nvcc failed: {' '.join(step)}\n{proc.stderr[-2000:]}")
    if not binary.is_file():
        raise RunnerBlocked("RUNNER_BLOCKED: harness binary missing after build")
    return binary


def scalar_matches(got: float, want: float) -> bool:
    """Cell-tolerance comparison for the completed scalar sum."""
    return math.isfinite(got) and abs(got - want) <= ATOL + RTOL * abs(want)


def deterministic_inputs(n: int) -> array.array:
    """Seed-20260914 FP32-range input buffer. Mirrors reduction_runner.deterministic_inputs."""
    if n <= 0:
        raise RunnerBlocked("RUNNER_BLOCKED: non-positive input size")
    rng = random.Random(SEED)
    return array.array("f", (rng.uniform(-1.0, 1.0) for _ in range(n)))


def run_candidate(source_root: Path, regime: str, candidate_id: str, workdir: Path) -> dict:
    """Build the harness, dispatch the pinned BlockReduce geometry, validate the sum."""
    from cub_block_adapter import cell_descriptor
    from correctness_reference import ref_cub_block_reduce

    source_file, revision = verify_source(source_root)
    actual_test_hash = sha256_file(source_file)
    descriptor = cell_descriptor(regime, candidate_id)
    nvcc = find_nvcc()
    meta = descriptor["build"]["compile_meta"]
    block_x, items = int(meta["block_dim_x"]), int(meta["items_per_thread"])
    if (block_x, items) != CANDIDATE_GEOMETRY[candidate_id]:
        raise RunnerBlocked(f"RUNNER_BLOCKED: geometry {(block_x, items)} is not admitted candidate {candidate_id}")
    binary = build_binary(source_root, workdir, nvcc, block_x, items)
    in_arr = deterministic_inputs(1024)
    in_path, o_path = workdir / "in.bin", workdir / "out.bin"
    with open(in_path, "wb") as f:
        in_arr.tofile(f)
    proc = subprocess.run([str(binary), "1024", str(in_path), str(o_path)],
                          capture_output=True, text=True)
    if proc.returncode != 0:
        raise RunnerBlocked(f"RUNNER_BLOCKED: harness run failed: {proc.stderr[-2000:]}")
    out = array.array("f")
    with open(o_path, "rb") as f:
        out.fromfile(f, 1)
    if len(out) != 1 or not math.isfinite(out[0]):
        raise RunnerBlocked("RUNNER_BLOCKED: output shape/finiteness check failed")
    expected = ref_cub_block_reduce(list(in_arr))[0]
    if not scalar_matches(out[0], expected):
        raise RuntimeError(f"CORRUPT_OUTPUT_REJECTED: got {out[0]}, want {expected}")
    # Status mirrors the catalog row: runner exists and is CPU-tested, GPU
    # validation pending (CUDA-samples precedent M274/M277). Promote to
    # compiled_gpu_verified only on coordinator acceptance of GPU evidence.
    result = {
        "status": "implemented_unvalidated_runtime",
        "source_revision": revision,
        "source_test_sha256": actual_test_hash,
        "source_path": TEST_REL,
        "regime": regime,
        "candidate_id": candidate_id,
        "n_elements": 1024,
        "controls": {"block_dim_x": block_x, "items_per_thread": items},
        "build": {"nvcc": nvcc, "arch": "sm_120", "std": "c++17",
                  "include": "pinned CUB headers (<cccl>/cub)",
                  "defines": [f"HARNESS_BLOCK_X={block_x}", f"HARNESS_ITEMS_PER_THREAD={items}", "HARNESS_VALID_ITEMS=1024"],
                  "note": "pinned bytes unmodified; Catch2 test binary never built; "
                          "driver owns main and instantiates cub::BlockReduce as the test does"},
        "reference": {"elements_checked": 1024, "rtol": RTOL, "atol": ATOL,
                      "completion": "single block; device scalar is the completed sum"},
        "runtime": {
            "python": platform.python_version(),
        },
    }
    return result


def prepare_binary_energy_context(source_root: Path, regime: str, candidate_id: str, workdir: Path):
    """Build once, return a BinaryEnergyContext for energy_harness/application_energy_harness.py.
    Mirrors run_candidate()'s setup exactly; does not invoke the binary itself."""
    hpc_dir = Path(__file__).resolve().parents[2] / "energy_harness"
    if str(hpc_dir) not in sys.path:
        sys.path.insert(0, str(hpc_dir))
    from application_energy_harness import BinaryEnergyContext

    from cub_block_adapter import cell_descriptor
    from correctness_reference import ref_cub_block_reduce

    source_file, revision = verify_source(source_root)
    actual_test_hash = sha256_file(source_file)
    descriptor = cell_descriptor(regime, candidate_id)
    nvcc = find_nvcc()
    meta = descriptor["build"]["compile_meta"]
    block_x, items = int(meta["block_dim_x"]), int(meta["items_per_thread"])
    if (block_x, items) != CANDIDATE_GEOMETRY[candidate_id]:
        raise RunnerBlocked(f"RUNNER_BLOCKED: geometry {(block_x, items)} is not admitted candidate {candidate_id}")
    binary = build_binary(source_root, workdir, nvcc, block_x, items)
    in_arr = deterministic_inputs(1024)
    in_path, o_path = workdir / "in.bin", workdir / "out.bin"
    with open(in_path, "wb") as f:
        in_arr.tofile(f)
    expected = ref_cub_block_reduce(list(in_arr))[0]

    def check():
        out = array.array("f")
        with open(o_path, "rb") as f:
            out.fromfile(f, 1)
        return len(out) == 1 and math.isfinite(out[0]) and scalar_matches(out[0], expected)

    return BinaryEnergyContext(
        parent_id="train_cub_block_reduce", regime=regime, candidate_id=candidate_id,
        source_revision=revision, source_sha256=actual_test_hash, source_path=TEST_REL,
        controls={"block_dim_x": block_x, "items_per_thread": items},
        runtime_info={"python": platform.python_version(), "nvcc": nvcc, "arch": "sm_120"},
        binary=binary, argv_prefix=["1024", str(in_path), str(o_path)], check=check,
    )


def self_test() -> None:
    from cub_block_adapter import cell_descriptor
    from correctness_reference import ref_cub_block_reduce

    with tempfile.TemporaryDirectory() as temp:
        fixture = Path(temp) / "source.cu"
        fixture.write_bytes(b"pinned fixture")
        expected = sha256_file(fixture)
        assert expected != PINNED_TEST_SHA256
        assert sha256_file(fixture) == expected
        fixture.write_bytes(b"corrupt fixture")
        assert sha256_file(fixture) != expected
    assert "DRIVER_TEMPLATE" in globals() and "BlockReduce" in DRIVER_TEMPLATE
    assert "int main(int argc" in DRIVER_TEMPLATE  # driver owns main; Catch2 main never built
    assert "CUBLAS" not in DRIVER_TEMPLATE and "cublas" not in DRIVER_TEMPLATE
    for regime in ("small", "medium", "large"):
        for candidate in ("c1", "c2", "c3", "c4"):
            d = cell_descriptor(regime, candidate)
            assert d["source_status"] == "source_verified"
            assert d["implementation_status"] == "implemented_unvalidated_runtime"
            assert d["semantics"]["same_problem_across_candidates"]
    assert ref_cub_block_reduce([1.0, 2.0, 3.0]) == [6.0]
    x = deterministic_inputs(64)
    assert len(x) == 64
    assert list(x) == list(deterministic_inputs(64))
    expected = ref_cub_block_reduce(list(x))[0]
    assert scalar_matches(expected, expected)
    assert not scalar_matches(expected + 1.0, expected)
    assert not scalar_matches(float("nan"), expected)
    print("CPU_ONLY_CUB_BLOCK_RUNNER_OK: hash/descriptor/determinism/reference checks passed")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", type=Path)
    parser.add_argument("--regime", choices=("small", "medium", "large"))
    parser.add_argument("--candidate", choices=("c1", "c2", "c3", "c4"))
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--workdir", type=Path, default=None)
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return 0
    if args.source_root is None or args.regime is None or args.candidate is None:
        parser.error("--source-root, --regime, and --candidate are required unless --self-test")
    try:
        with tempfile.TemporaryDirectory(prefix="cub_block_harness_") as temp:
            workdir = args.workdir or Path(temp)
            workdir.mkdir(parents=True, exist_ok=True)
            print(json.dumps(run_candidate(args.source_root, args.regime, args.candidate, workdir),
                             sort_keys=True))
    except RunnerBlocked as exc:
        print(str(exc), file=sys.stderr)
        return 3
    return 0


if __name__ == "__main__":
    main()
