#!/usr/bin/env python3
"""Run the pinned CUDA Samples reduction kernels, when a real CUDA toolchain is present.

The repository deliberately contains no CUDA dependency.  This runner therefore
has a strict two-state contract: source, toolchain and runtime checks either
pass and the actual pinned sample kernels launch, or the command fails loudly
without downloading, installing, substituting an implementation, or executing
the sample's own benchmark main (timing loops, bandwidth prints, multi-kernel
sweep).

Build model (documented because it is unusual): the pinned
``reduction_kernel.cu`` holds the kernels, the ``reduce<T>()`` host dispatcher,
and the explicit ``float`` instantiation, and contains no ``main``; the pinned
``reduction.cpp`` holds ``main`` plus the ``isPow2`` helper the dispatcher may
call.  ``reduction.cpp`` is compiled with ``-Dmain=reduction_sample_main_disabled``
(a build flag that renames the sample entry point; the pinned bytes are never
modified), then linked with ``reduction_kernel.o`` and our harness driver below,
which owns ``main``, deterministic inputs, the catalog launch geometry, the
single-pass dispatch, host completion of the partial sums (the sample's
``--cpufinal`` mode), and full-output comparison.  All build flags are recorded
in every result for exact reproduction.
"""
from __future__ import annotations

import argparse
import array
import hashlib
import json
import math
import platform
import random
import subprocess
import sys
import tempfile
from pathlib import Path

import cuda_build_target

ROOT = Path(__file__).resolve().parent
KERNEL_REL = "cpp/2_Concepts_and_Techniques/reduction/reduction_kernel.cu"
UTIL_REL = "cpp/2_Concepts_and_Techniques/reduction/reduction.cpp"
HEADER_REL = "cpp/2_Concepts_and_Techniques/reduction/reduction.h"
PINNED_REVISION = "5443602d89ed99aede2e4b7bf329daddeadb320e"
PINNED_KERNEL_SHA256 = "c9ac9a9a424726522dd616fa24d58e6f0919ac95dd746a233d5fb857bffffde9"
PINNED_UTIL_SHA256 = "a416ae8aa45a9c521125ecb74343f426f1fa264479192076817e4ca536afbdba"
SEED = 20260914
RTOL = 1e-5
ATOL = 1e-6

# Catalog candidates c1..c4 map to sample whichKernel 2,3,4,5 (all full-sum
# single-pass kernels with host completion; cooperative/multi-warp variants
# 7/9 and the benchmark sweep are excluded).
CANDIDATE_KERNELS = {"c1": 2, "c2": 3, "c3": 4, "c4": 5}

DRIVER_TEMPLATE = r"""
// Harness driver for pinned reduction sample kernels (generated by reduction_runner.py).
// Owns main(), deterministic inputs, launch geometry, single-pass dispatch, host
// completion of per-block partials (--cpufinal mode), and result dump. Compute kernels
// and the reduce<>() dispatcher are linked from the pinned, byte-unmodified objects.
//
// Optional energy-measurement mode (--repeat/--graph-batch/--trace-dir, all three
// required together): captures graph_batch launches into one CUDA graph and replays
// it, mirroring Task B's fixtures and Task C's Python-callable runners' torch.cuda.
// CUDAGraph path (M311) -- a plain host-enqueue loop was found to spend 53-87% of its
// window on launch submission for microbenchmark-scale kernels (M310). The pinned
// reduce<T>() dispatcher (reduction.h) takes no stream argument and always launches on
// the default stream. CUDA does not allow capturing the LEGACY default stream (first GPU
// run, M319: beginning capture on stream 0 -> "operation not permitted when stream is
// capturing"), so build_binary() compiles every object with --default-stream per-thread:
// the same unmodified launches then go to cudaStreamPerThread, which is capturable, and
// capture, replay, remainder launches and timing events all use that one stream.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cuda_runtime.h>

#include "reduction.h"

#define CUDA_CHECK(call) do { cudaError_t s_ = (call); \
    if (s_ != cudaSuccess) { std::fprintf(stderr, "FATAL CUDA %s:%d: %s\n", \
    __FILE__, __LINE__, cudaGetErrorString(s_)); std::exit(2); } } while (0)

static long long monotonic_ns() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000000000LL + ts.tv_nsec;
}

int main(int argc, char **argv) {
    if (argc != 7 && argc != 13) {
        std::fprintf(stderr, "usage: %s <size> <threads> <blocks> <which_kernel> <in.bin> <out.bin> "
                     "[--repeat N --graph-batch B --trace-dir DIR]\n", argv[0]);
        return 2;
    }
    const int size = std::atoi(argv[1]);
    const int threads = std::atoi(argv[2]);
    const int blocks = std::atoi(argv[3]);
    const int which_kernel = std::atoi(argv[4]);
    if (size <= 0 || threads <= 0 || blocks <= 0) {
        std::fprintf(stderr, "FATAL: bad geometry\n"); return 2;
    }
    FILE *fi = std::fopen(argv[5], "rb");
    if (!fi) { std::fprintf(stderr, "FATAL: cannot open input\n"); return 2; }
    float *h_in = (float *)std::malloc((size_t)size * sizeof(float));
    float *h_part = (float *)std::malloc((size_t)blocks * sizeof(float));
    if (!h_in || !h_part) { std::fprintf(stderr, "FATAL: host alloc\n"); return 2; }
    if (std::fread(h_in, sizeof(float), size, fi) != (size_t)size) {
        std::fprintf(stderr, "FATAL: short input read\n"); return 2;
    }
    std::fclose(fi);
    float *d_in, *d_out;
    CUDA_CHECK(cudaMalloc(&d_in, (size_t)size * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, (size_t)blocks * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, (size_t)size * sizeof(float), cudaMemcpyHostToDevice));

    long long repeat = 0, graph_batch = 0;
    const char *trace_dir = nullptr;
    if (argc == 13) {
        if (std::strcmp(argv[7], "--repeat") != 0 || std::strcmp(argv[9], "--graph-batch") != 0 ||
            std::strcmp(argv[11], "--trace-dir") != 0) {
            std::fprintf(stderr, "FATAL: expected --repeat N --graph-batch B --trace-dir DIR\n");
            return 2;
        }
        repeat = std::atoll(argv[8]);
        graph_batch = std::atoll(argv[10]);
        trace_dir = argv[12];
        if (repeat <= 0 || graph_batch <= 0) { std::fprintf(stderr, "FATAL: bad repeat/graph-batch\n"); return 2; }
    }

    if (trace_dir == nullptr) {
        reduce<float>(size, threads, blocks, which_kernel, d_in, d_out);
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaDeviceSynchronize());
    } else {
        cudaGraph_t graph;
        cudaGraphExec_t graph_exec;
        CUDA_CHECK(cudaStreamBeginCapture(cudaStreamPerThread, cudaStreamCaptureModeGlobal));
        for (long long i = 0; i < graph_batch; ++i) {
            reduce<float>(size, threads, blocks, which_kernel, d_in, d_out);
        }
        CUDA_CHECK(cudaStreamEndCapture(cudaStreamPerThread, &graph));
        CUDA_CHECK(cudaGraphInstantiate(&graph_exec, graph, nullptr, nullptr, 0));

        // Replay, the remainder launches and the timing events all use the same per-thread stream
        // so they are ordered by construction (no reliance on legacy-stream implicit sync).
        const cudaStream_t replay_stream = cudaStreamPerThread;
        CUDA_CHECK(cudaGraphLaunch(graph_exec, replay_stream));  // warm-up, discarded
        CUDA_CHECK(cudaStreamSynchronize(replay_stream));

        cudaEvent_t ev_begin, ev_end;
        CUDA_CHECK(cudaEventCreate(&ev_begin));
        CUDA_CHECK(cudaEventCreate(&ev_end));
        const long long full_replays = repeat / graph_batch;
        const long long remainder = repeat % graph_batch;
        const long long host_begin_ns = monotonic_ns();
        CUDA_CHECK(cudaEventRecord(ev_begin, replay_stream));
        for (long long r = 0; r < full_replays; ++r) {
            CUDA_CHECK(cudaGraphLaunch(graph_exec, replay_stream));
        }
        for (long long i = 0; i < remainder; ++i) {
            reduce<float>(size, threads, blocks, which_kernel, d_in, d_out);
        }
        CUDA_CHECK(cudaEventRecord(ev_end, replay_stream));
        CUDA_CHECK(cudaEventSynchronize(ev_end));
        const long long host_end_ns = monotonic_ns();
        float elapsed_ms = 0.0f;
        CUDA_CHECK(cudaEventElapsedTime(&elapsed_ms, ev_begin, ev_end));

        char windows_path[4096];
        std::snprintf(windows_path, sizeof(windows_path), "%s/windows.csv", trace_dir);
        FILE *fw = std::fopen(windows_path, "w");
        if (!fw) { std::fprintf(stderr, "FATAL: cannot open windows.csv\n"); return 2; }
        std::fprintf(fw, "block,launches,host_begin_monotonic_ns,host_end_monotonic_ns,cuda_seconds\n");
        std::fprintf(fw, "1,%lld,%lld,%lld,%.9f\n", repeat, host_begin_ns, host_end_ns,
                     (double)elapsed_ms / 1000.0);
        std::fclose(fw);

        CUDA_CHECK(cudaGraphExecDestroy(graph_exec));
        CUDA_CHECK(cudaGraphDestroy(graph));
    }

    CUDA_CHECK(cudaMemcpy(h_part, d_out, (size_t)blocks * sizeof(float), cudaMemcpyDeviceToHost));
    double total = 0.0;
    for (int i = 0; i < blocks; ++i) total += (double)h_part[i];
    FILE *fo = std::fopen(argv[6], "wb");
    if (!fo) { std::fprintf(stderr, "FATAL: cannot open output\n"); return 2; }
    float total_f = (float)total;
    if (std::fwrite(&total_f, sizeof(float), 1, fo) != 1) {
        std::fprintf(stderr, "FATAL: short output write\n"); return 2;
    }
    std::fclose(fo);
    std::printf("REDUCE_DONE size=%d threads=%d blocks=%d kernel=%d partials=%d\n",
                size, threads, blocks, which_kernel, blocks);
    return 0;
}
"""


class RunnerBlocked(RuntimeError):
    """A required provenance/toolchain/runtime check failed; never silently fall back."""


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def verify_source(source_root: Path) -> tuple[Path, str]:
    """Verify exact Git revision and sample bytes before compiling anything."""
    source_root = source_root.expanduser().resolve()
    kernel_file = source_root / KERNEL_REL
    util_file = source_root / UTIL_REL
    header_file = source_root / HEADER_REL
    for path in (kernel_file, util_file, header_file):
        if not path.is_file():
            raise RunnerBlocked(f"RUNNER_BLOCKED: missing pinned source {path}")
    try:
        revision = subprocess.run(
            ["git", "-C", str(source_root), "rev-parse", "HEAD"],
            check=True, capture_output=True, text=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RunnerBlocked("RUNNER_BLOCKED: source_root is not a readable Git checkout") from exc
    if revision != PINNED_REVISION:
        raise RunnerBlocked(f"RUNNER_BLOCKED: expected revision {PINNED_REVISION}, got {revision}")
    for path, expected, name in ((kernel_file, PINNED_KERNEL_SHA256, "kernel"),
                                 (util_file, PINNED_UTIL_SHA256, "util")):
        actual_hash = sha256_file(path)
        if actual_hash != expected:
            raise RunnerBlocked(f"RUNNER_BLOCKED: {name} SHA-256 mismatch: expected {expected}, got {actual_hash}")
    return kernel_file, revision


def find_nvcc() -> str:
    """Locate nvcc and check the build arch against the target GPU (cuda_build_target.py)."""
    nvcc = cuda_build_target.find_nvcc(RunnerBlocked)
    cuda_build_target.assert_live_arch(build_arch(), RunnerBlocked)
    return nvcc


def build_arch() -> str:
    """sm_120 (Blackwell) unless HARNESS_CUDA_ARCH says otherwise."""
    return cuda_build_target.target_arch(RunnerBlocked)


# The pinned reduce<T>() launches on the default stream; the per-thread default stream makes those
# launches capturable into a CUDA graph (legacy stream 0 is not). The kernels themselves are unchanged.
DEFAULT_STREAM_FLAGS = ["--default-stream", "per-thread"]


def build_binary(source_root: Path, workdir: Path, nvcc: str) -> Path:
    """Compile pinned kernel + util objects (sample main renamed away), link driver."""
    kernel_src = source_root / KERNEL_REL
    util_src = source_root / UTIL_REL
    header_dir = kernel_src.parent
    common_inc = source_root / "Common"
    if not common_inc.is_dir():
        raise RunnerBlocked(f"RUNNER_BLOCKED: missing helper headers at {common_inc}")
    driver_src = workdir / "reduction_driver.cu"
    driver_src.write_text(DRIVER_TEMPLATE, encoding="utf-8")
    kernel_obj = workdir / "reduction_kernel.o"
    util_obj = workdir / "reduction_util.o"
    binary = workdir / "reduction_harness"
    steps = [
        [nvcc, "-O2", f"-arch={build_arch()}", *DEFAULT_STREAM_FLAGS, "-I", str(common_inc), "-I", str(header_dir),
         "-c", str(kernel_src), "-o", str(kernel_obj)],
        [nvcc, "-O2", f"-arch={build_arch()}", *DEFAULT_STREAM_FLAGS, "-I", str(common_inc), "-I", str(header_dir),
         "-Dmain=reduction_sample_main_disabled",
         "-c", str(util_src), "-o", str(util_obj)],
        [nvcc, "-O2", f"-arch={build_arch()}", *DEFAULT_STREAM_FLAGS, "-I", str(header_dir),
         str(driver_src), str(kernel_obj), str(util_obj),
         "-o", str(binary)],
    ]
    for step in steps:
        proc = subprocess.run(step, capture_output=True, text=True, cwd=str(workdir))
        if proc.returncode != 0:
            raise RunnerBlocked(f"RUNNER_BLOCKED: nvcc failed: {' '.join(step)}\n{proc.stderr[-2000:]}")
    if not binary.is_file():
        raise RunnerBlocked("RUNNER_BLOCKED: harness binary missing after build")
    return binary


def scalar_matches(got: float, want: float) -> bool:
    """Cell-tolerance comparison for the completed scalar sum."""
    return math.isfinite(got) and abs(got - want) <= ATOL + RTOL * abs(want)


def deterministic_inputs(n: int) -> array.array:
    """Seed-20260914 FP32-range input buffer. Single source of truth for inputs."""
    if n <= 0:
        raise RunnerBlocked("RUNNER_BLOCKED: non-positive input size")
    rng = random.Random(SEED)
    return array.array("f", (rng.uniform(-1.0, 1.0) for _ in range(n)))


def run_candidate(source_root: Path, regime: str, candidate_id: str, workdir: Path) -> dict:
    """Build the harness, dispatch the pinned kernel, validate the completed sum."""
    from reduction_adapter import cell_descriptor
    from correctness_reference import ref_sum

    source_file, revision = verify_source(source_root)
    actual_kernel_hash = sha256_file(source_file)
    descriptor = cell_descriptor(regime, candidate_id)
    nvcc = find_nvcc()
    binary = build_binary(source_root, workdir, nvcc)
    controls = descriptor["build"]["compile_meta"]
    size = int(descriptor["launch"]["runtime_args"][0].split("=")[1])
    threads = int(controls["threads"])
    blocks = int(controls["blocks"])
    which_kernel = int(controls["which_kernel"])
    if which_kernel not in CANDIDATE_KERNELS.values():
        raise RunnerBlocked(f"RUNNER_BLOCKED: kernel {which_kernel} is not an admitted full-sum candidate")
    in_arr = deterministic_inputs(size)
    in_path, o_path = workdir / "in.bin", workdir / "out.bin"
    with open(in_path, "wb") as f:
        in_arr.tofile(f)
    proc = subprocess.run(
        [str(binary), str(size), str(threads), str(blocks), str(which_kernel),
         str(in_path), str(o_path)],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        raise RunnerBlocked(f"RUNNER_BLOCKED: harness run failed: {proc.stderr[-2000:]}")
    out = array.array("f")
    with open(o_path, "rb") as f:
        out.fromfile(f, 1)
    if len(out) != 1 or not math.isfinite(out[0]):
        raise RunnerBlocked("RUNNER_BLOCKED: output shape/finiteness check failed")
    expected = ref_sum(list(in_arr))[0]
    if not scalar_matches(out[0], expected):
        raise RuntimeError(
            f"CORRUPT_OUTPUT_REJECTED: got {out[0]}, want {expected}")
    # Status reflects coordinator-accepted GPU validation 2026-09-19 (12/12 cells).
    # Do not revert without coordinator direction.
    result = {
        "status": "compiled_gpu_verified",
        "source_revision": revision,
        "source_kernel_sha256": actual_kernel_hash,
        "source_path": KERNEL_REL,
        "regime": regime,
        "candidate_id": candidate_id,
        "n_elements": size,
        "controls": {"threads": threads, "blocks": blocks, "which_kernel": which_kernel},
        "build": {"nvcc": nvcc, "arch": build_arch(),
                  "defines": ["main=reduction_sample_main_disabled (util object only)"],
                  "note": "pinned bytes unmodified; kernel object has no main; "
                          "sample main renamed at compile time only"},
        "reference": {"elements_checked": size, "rtol": RTOL, "atol": ATOL,
                      "completion": "host sum over per-block partials (sample --cpufinal mode)"},
        "runtime": {
            "python": platform.python_version(),
        },
    }
    return result


def prepare_binary_energy_context(source_root: Path, regime: str, candidate_id: str, workdir: Path):
    """Build once, return a BinaryEnergyContext for energy_harness/application_energy_harness.py.
    Mirrors run_candidate()'s setup exactly; does not invoke the binary itself."""
    hpc_dir = Path(__file__).resolve().parents[2] / "energy_harness"
    if str(hpc_dir) not in sys.path:
        sys.path.insert(0, str(hpc_dir))
    from application_energy_harness import BinaryEnergyContext

    from reduction_adapter import cell_descriptor
    from correctness_reference import ref_sum

    source_file, revision = verify_source(source_root)
    actual_kernel_hash = sha256_file(source_file)
    descriptor = cell_descriptor(regime, candidate_id)
    nvcc = find_nvcc()
    binary = build_binary(source_root, workdir, nvcc)
    controls = descriptor["build"]["compile_meta"]
    size = int(descriptor["launch"]["runtime_args"][0].split("=")[1])
    threads = int(controls["threads"])
    blocks = int(controls["blocks"])
    which_kernel = int(controls["which_kernel"])
    if which_kernel not in CANDIDATE_KERNELS.values():
        raise RunnerBlocked(f"RUNNER_BLOCKED: kernel {which_kernel} is not an admitted full-sum candidate")
    in_arr = deterministic_inputs(size)
    in_path, o_path = workdir / "in.bin", workdir / "out.bin"
    with open(in_path, "wb") as f:
        in_arr.tofile(f)
    expected = ref_sum(list(in_arr))[0]

    def check():
        out = array.array("f")
        with open(o_path, "rb") as f:
            out.fromfile(f, 1)
        return len(out) == 1 and math.isfinite(out[0]) and scalar_matches(out[0], expected)

    return BinaryEnergyContext(
        parent_id="train_cuda_samples_reduction", regime=regime, candidate_id=candidate_id,
        source_revision=revision, source_sha256=actual_kernel_hash, source_path=KERNEL_REL,
        controls={"threads": threads, "blocks": blocks, "which_kernel": which_kernel},
        runtime_info={"python": platform.python_version(), "nvcc": nvcc, "arch": build_arch()},
        binary=binary,
        argv_prefix=[str(size), str(threads), str(blocks), str(which_kernel), str(in_path), str(o_path)],
        check=check,
    )


def self_test() -> None:
    from reduction_adapter import cell_descriptor

    with tempfile.TemporaryDirectory() as temp:
        fixture = Path(temp) / "source.py"
        fixture.write_bytes(b"pinned fixture")
        expected = sha256_file(fixture)
        assert sha256_file(fixture) == expected
        fixture.write_bytes(b"corrupt fixture")
        assert sha256_file(fixture) != expected
    assert "DRIVER_TEMPLATE" in globals() and "reduce<float>" in DRIVER_TEMPLATE
    assert "int main(int argc" in DRIVER_TEMPLATE  # driver owns main; sample main renamed at build
    assert "-Dmain=" not in DRIVER_TEMPLATE  # the define lives in build_binary, documented there
    # M319: capturing the legacy default stream is illegal; capture must use the per-thread stream.
    assert "cudaStreamBeginCapture(0" not in DRIVER_TEMPLATE and "cudaStreamEndCapture(0" not in DRIVER_TEMPLATE
    assert "cudaStreamBeginCapture(cudaStreamPerThread" in DRIVER_TEMPLATE
    assert DEFAULT_STREAM_FLAGS == ["--default-stream", "per-thread"]
    # The per-thread stream is not ours to destroy (cudaStreamDestroy -> "invalid resource handle" on GPU).
    assert "cudaStreamDestroy" not in DRIVER_TEMPLATE
    for regime in ("small", "medium", "large"):
        for candidate in ("c1", "c2", "c3", "c4"):
            d = cell_descriptor(regime, candidate)
            assert d["source_status"] == "source_verified"
            assert d["implementation_status"] == "compiled_gpu_verified"
            assert d["semantics"]["same_problem_across_candidates"]
    from correctness_reference import ref_sum
    assert ref_sum([1.0, 2.0, 3.0]) == [6.0]
    x = deterministic_inputs(64)
    assert len(x) == 64
    assert list(x) == list(deterministic_inputs(64))
    expected = ref_sum(list(x))[0]
    assert scalar_matches(expected, expected)
    assert not scalar_matches(expected + 1.0, expected)
    assert not scalar_matches(float("nan"), expected)
    print("CPU_ONLY_REDUCTION_RUNNER_OK: hash/descriptor/determinism/reference checks passed")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", type=Path)
    parser.add_argument("--regime", choices=("small", "medium", "large"))
    parser.add_argument("--candidate", choices=("c1", "c2", "c3", "c4"))
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--workdir", type=Path, default=None)
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return 0
    if args.source_root is None or args.regime is None or args.candidate is None:
        parser.error("--source-root, --regime, and --candidate are required unless --self-test")
    try:
        with tempfile.TemporaryDirectory(prefix="reduction_harness_") as temp:
            workdir = args.workdir or Path(temp)
            workdir.mkdir(parents=True, exist_ok=True)
            print(json.dumps(run_candidate(args.source_root, args.regime, args.candidate, workdir),
                             sort_keys=True))
    except RunnerBlocked as exc:
        print(str(exc), file=sys.stderr)
        return 3
    return 0


if __name__ == "__main__":
    main()
