#!/usr/bin/env python3
"""Run the pinned CUDA Samples transpose kernels, when a real CUDA toolchain is present.

The repository deliberately contains no CUDA dependency.  This runner therefore
has a strict two-state contract: source, toolchain and runtime checks either
pass and the actual pinned sample kernels launch, or the command fails loudly
without downloading, installing, substituting an implementation, or executing
the sample's own benchmark main (timing loops, bandwidth prints, coarse/fine
partial kernels).

Build model (documented because it is unusual): the pinned ``transpose.cu``
contains the kernels plus the sample ``main``.  Kernel objects are compiled
with ``-Dmain=transpose_sample_main_disabled`` (a build flag that renames the
sample entry point; the pinned bytes are never modified), then linked against
our harness driver below, which owns ``main``, deterministic inputs, the
catalog launch geometry, and full-output comparison.  All build flags are
recorded in every result for exact reproduction.

Launch geometry (audited): every full-transpose kernel steps its tile loops by
the hardcoded BLOCK_ROWS=16, so blocks are dim3(32, 16) = 512 threads with grid
dim3(dim_x/32, dim_y/32). A 256-thread block would cover only half of each
32-row tile. The sample main launches identically.
"""
from __future__ import annotations

import argparse
import array
import hashlib
import json
import platform
import subprocess
import sys
import tempfile
from pathlib import Path

import cuda_build_target

ROOT = Path(__file__).resolve().parent
SOURCE_REL = "cpp/6_Performance/transpose/transpose.cu"
PINNED_REVISION = "5443602d89ed99aede2e4b7bf329daddeadb320e"
PINNED_SHA256 = "ba300b6b5f4dbc17ec72bfd3d1ee082508632ec431fe46ba54e6e3ce05292a95"
SEED = 20260914
RTOL = 1e-5
ATOL = 1e-6

# Catalog candidates c1..c4 map to sample kernel variants 2,3,4,7 (all full
# transposes; copy/shared-copy/coarse/fine partial kernels are excluded).
VARIANT_KERNELS = {2: "transposeNaive", 3: "transposeCoalesced",
                   4: "transposeNoBankConflicts", 7: "transposeDiagonal"}

DRIVER_TEMPLATE = r"""
// Harness driver for pinned transpose sample kernels (generated by transpose_runner.py).
// Owns main(), deterministic inputs, launch geometry, and result dump. Compute kernels
// are linked from the pinned, byte-unmodified transpose.cu object. Variant dispatch
// mirrors the sample's own switch (full transposes only; partial kernels excluded).
//
// Optional energy-measurement mode (--repeat/--graph-batch/--trace-dir, all three
// required together): captures graph_batch launches into one CUDA graph on a private
// stream and replays it, mirroring Task B's fixtures and Task C's Python-callable
// runners' torch.cuda.CUDAGraph path (M311) -- a plain host-enqueue loop was found to
// spend 53-87% of its window on launch submission for microbenchmark-scale kernels
// (M310), so this driver captures a graph from the start. With no --repeat, the
// single-shot correctness path below is byte-for-byte unchanged.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cuda_runtime.h>

__global__ void transposeNaive(float *odata, float *idata, int width, int height);
__global__ void transposeCoalesced(float *odata, float *idata, int width, int height);
__global__ void transposeNoBankConflicts(float *odata, float *idata, int width, int height);
__global__ void transposeDiagonal(float *odata, float *idata, int width, int height);

#define CUDA_CHECK(call) do { cudaError_t s_ = (call); \
    if (s_ != cudaSuccess) { std::fprintf(stderr, "FATAL CUDA %s:%d: %s\n", \
    __FILE__, __LINE__, cudaGetErrorString(s_)); std::exit(2); } } while (0)

static long long monotonic_ns() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000000000LL + ts.tv_nsec;
}

static bool launch_variant(int variant, dim3 grid, dim3 threads, cudaStream_t stream,
                           float *d_out, float *d_in, int dim_x, int dim_y) {
    switch (variant) {
        case 2: transposeNaive<<<grid, threads, 0, stream>>>(d_out, d_in, dim_x, dim_y); return true;
        case 3: transposeCoalesced<<<grid, threads, 0, stream>>>(d_out, d_in, dim_x, dim_y); return true;
        case 4: transposeNoBankConflicts<<<grid, threads, 0, stream>>>(d_out, d_in, dim_x, dim_y); return true;
        case 7: transposeDiagonal<<<grid, threads, 0, stream>>>(d_out, d_in, dim_x, dim_y); return true;
        default: return false;
    }
}

int main(int argc, char **argv) {
    if (argc != 6 && argc != 12) {
        std::fprintf(stderr, "usage: %s <dim_x> <dim_y> <variant> <in.bin> <out.bin> "
                     "[--repeat N --graph-batch B --trace-dir DIR]\n", argv[0]);
        return 2;
    }
    const int dim_x = std::atoi(argv[1]);
    const int dim_y = std::atoi(argv[2]);
    const int variant = std::atoi(argv[3]);
    if (dim_x <= 0 || dim_y <= 0) { std::fprintf(stderr, "FATAL: bad dims\n"); return 2; }
    if (dim_x % 32 != 0 || dim_y % 32 != 0) {
        std::fprintf(stderr, "FATAL: dims must be multiples of TILE_DIM=32\n"); return 2;
    }
    const int n = dim_x * dim_y;
    FILE *fi = std::fopen(argv[4], "rb");
    if (!fi) { std::fprintf(stderr, "FATAL: cannot open input\n"); return 2; }
    float *h_in = (float *)std::malloc((size_t)n * sizeof(float));
    float *h_out = (float *)std::malloc((size_t)n * sizeof(float));
    if (!h_in || !h_out) { std::fprintf(stderr, "FATAL: host alloc\n"); return 2; }
    if (std::fread(h_in, sizeof(float), n, fi) != (size_t)n) {
        std::fprintf(stderr, "FATAL: short input read\n"); return 2;
    }
    std::fclose(fi);
    float *d_in, *d_out;
    CUDA_CHECK(cudaMalloc(&d_in, (size_t)n * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, (size_t)n * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, (size_t)n * sizeof(float), cudaMemcpyHostToDevice));
    // Sample-native launch: grid covers dim/32 tiles per axis, 512-thread (32,16) blocks.
    dim3 grid(dim_x / 32, dim_y / 32, 1);
    dim3 threads(32, 16, 1);

    long long repeat = 0, graph_batch = 0;
    const char *trace_dir = nullptr;
    if (argc == 12) {
        if (std::strcmp(argv[6], "--repeat") != 0 || std::strcmp(argv[8], "--graph-batch") != 0 ||
            std::strcmp(argv[10], "--trace-dir") != 0) {
            std::fprintf(stderr, "FATAL: expected --repeat N --graph-batch B --trace-dir DIR\n");
            return 2;
        }
        repeat = std::atoll(argv[7]);
        graph_batch = std::atoll(argv[9]);
        trace_dir = argv[11];
        if (repeat <= 0 || graph_batch <= 0) { std::fprintf(stderr, "FATAL: bad repeat/graph-batch\n"); return 2; }
    }

    if (trace_dir == nullptr) {
        if (!launch_variant(variant, grid, threads, 0, d_out, d_in, dim_x, dim_y)) {
            std::fprintf(stderr, "FATAL: unsupported variant %d\n", variant); return 2;
        }
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaDeviceSynchronize());
    } else {
        cudaStream_t stream;
        CUDA_CHECK(cudaStreamCreate(&stream));
        if (!launch_variant(variant, grid, threads, stream, d_out, d_in, dim_x, dim_y)) {
            std::fprintf(stderr, "FATAL: unsupported variant %d\n", variant); return 2;
        }
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaStreamSynchronize(stream));  // probe launch above, discarded; also validates variant

        cudaGraph_t graph;
        cudaGraphExec_t graph_exec;
        CUDA_CHECK(cudaStreamBeginCapture(stream, cudaStreamCaptureModeGlobal));
        for (long long i = 0; i < graph_batch; ++i) {
            launch_variant(variant, grid, threads, stream, d_out, d_in, dim_x, dim_y);
        }
        CUDA_CHECK(cudaStreamEndCapture(stream, &graph));
        CUDA_CHECK(cudaGraphInstantiate(&graph_exec, graph, nullptr, nullptr, 0));
        CUDA_CHECK(cudaGraphLaunch(graph_exec, stream));  // warm-up, discarded
        CUDA_CHECK(cudaStreamSynchronize(stream));

        cudaEvent_t ev_begin, ev_end;
        CUDA_CHECK(cudaEventCreate(&ev_begin));
        CUDA_CHECK(cudaEventCreate(&ev_end));
        const long long full_replays = repeat / graph_batch;
        const long long remainder = repeat % graph_batch;
        const long long host_begin_ns = monotonic_ns();
        CUDA_CHECK(cudaEventRecord(ev_begin, stream));
        for (long long r = 0; r < full_replays; ++r) {
            CUDA_CHECK(cudaGraphLaunch(graph_exec, stream));
        }
        for (long long i = 0; i < remainder; ++i) {
            launch_variant(variant, grid, threads, stream, d_out, d_in, dim_x, dim_y);
        }
        CUDA_CHECK(cudaEventRecord(ev_end, stream));
        CUDA_CHECK(cudaEventSynchronize(ev_end));
        const long long host_end_ns = monotonic_ns();
        float elapsed_ms = 0.0f;
        CUDA_CHECK(cudaEventElapsedTime(&elapsed_ms, ev_begin, ev_end));

        char windows_path[4096];
        std::snprintf(windows_path, sizeof(windows_path), "%s/windows.csv", trace_dir);
        FILE *fw = std::fopen(windows_path, "w");
        if (!fw) { std::fprintf(stderr, "FATAL: cannot open windows.csv\n"); return 2; }
        std::fprintf(fw, "block,launches,host_begin_monotonic_ns,host_end_monotonic_ns,cuda_seconds\n");
        std::fprintf(fw, "1,%lld,%lld,%lld,%.9f\n", repeat, host_begin_ns, host_end_ns,
                     (double)elapsed_ms / 1000.0);
        std::fclose(fw);

        CUDA_CHECK(cudaGraphExecDestroy(graph_exec));
        CUDA_CHECK(cudaGraphDestroy(graph));
        CUDA_CHECK(cudaStreamDestroy(stream));
    }

    CUDA_CHECK(cudaMemcpy(h_out, d_out, (size_t)n * sizeof(float), cudaMemcpyDeviceToHost));
    FILE *fo = std::fopen(argv[5], "wb");
    if (!fo) { std::fprintf(stderr, "FATAL: cannot open output\n"); return 2; }
    if (std::fwrite(h_out, sizeof(float), n, fo) != (size_t)n) {
        std::fprintf(stderr, "FATAL: short output write\n"); return 2;
    }
    std::fclose(fo);
    std::printf("TRANSPOSE_DONE dim=%dx%d variant=%d\n", dim_x, dim_y, variant);
    return 0;
}
"""


class RunnerBlocked(RuntimeError):
    """A required provenance/toolchain/runtime check failed; never silently fall back."""


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def verify_source(source_root: Path) -> tuple[Path, str]:
    """Verify exact Git revision and sample bytes before compiling anything."""
    source_root = source_root.expanduser().resolve()
    source_file = source_root / SOURCE_REL
    if not source_file.is_file():
        raise RunnerBlocked(f"RUNNER_BLOCKED: missing pinned source {source_file}")
    try:
        revision = subprocess.run(
            ["git", "-C", str(source_root), "rev-parse", "HEAD"],
            check=True, capture_output=True, text=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RunnerBlocked("RUNNER_BLOCKED: source_root is not a readable Git checkout") from exc
    if revision != PINNED_REVISION:
        raise RunnerBlocked(f"RUNNER_BLOCKED: expected revision {PINNED_REVISION}, got {revision}")
    actual_hash = sha256_file(source_file)
    if actual_hash != PINNED_SHA256:
        raise RunnerBlocked(f"RUNNER_BLOCKED: source SHA-256 mismatch: expected {PINNED_SHA256}, got {actual_hash}")
    return source_file, revision


def find_nvcc() -> str:
    """Locate nvcc and check the build arch against the target GPU (cuda_build_target.py)."""
    nvcc = cuda_build_target.find_nvcc(RunnerBlocked)
    cuda_build_target.assert_live_arch(build_arch(), RunnerBlocked)
    return nvcc


def build_arch() -> str:
    """sm_120 (Blackwell) unless HARNESS_CUDA_ARCH says otherwise."""
    return cuda_build_target.target_arch(RunnerBlocked)


def build_binary(source_root: Path, workdir: Path, nvcc: str) -> Path:
    """Compile pinned kernel object (main renamed away) + harness driver, link."""
    kernel_src = source_root / SOURCE_REL
    common_inc = source_root / "Common"
    if not common_inc.is_dir():
        raise RunnerBlocked(f"RUNNER_BLOCKED: missing helper headers at {common_inc}")
    driver_src = workdir / "transpose_driver.cu"
    driver_src.write_text(DRIVER_TEMPLATE, encoding="utf-8")
    kernel_obj = workdir / "transpose_kernel.o"
    binary = workdir / "transpose_harness"
    steps = [
        [nvcc, "-O2", f"-arch={build_arch()}", "-Dmain=transpose_sample_main_disabled",
         "-I", str(common_inc), "-c", str(kernel_src), "-o", str(kernel_obj)],
        [nvcc, "-O2", f"-arch={build_arch()}", str(driver_src), str(kernel_obj),
         "-o", str(binary)],
    ]
    for step in steps:
        proc = subprocess.run(step, capture_output=True, text=True, cwd=str(workdir))
        if proc.returncode != 0:
            raise RunnerBlocked(f"RUNNER_BLOCKED: nvcc failed: {' '.join(step)}\n{proc.stderr[-2000:]}")
    if not binary.is_file():
        raise RunnerBlocked("RUNNER_BLOCKED: harness binary missing after build")
    return binary


def deterministic_inputs(rows: int, cols: int) -> array.array:
    """Closed-form deterministic input matching ref_cuda_transpose's default
    (float(i % 8192)). No seed needed; identical values by construction."""
    n = rows * cols
    if n <= 0:
        raise RunnerBlocked("RUNNER_BLOCKED: non-positive matrix size")
    return array.array("f", (float(i % 8192) for i in range(n)))


def run_candidate(source_root: Path, regime: str, candidate_id: str, workdir: Path) -> dict:
    """Build the harness, launch the pinned kernel variant, validate every output element."""
    from transpose_adapter import cell_descriptor
    from correctness_reference import cuda_transpose_output_matches, ref_cuda_transpose

    source_file, revision = verify_source(source_root)
    actual_hash = sha256_file(source_file)
    descriptor = cell_descriptor(regime, candidate_id)
    nvcc = find_nvcc()
    binary = build_binary(source_root, workdir, nvcc)
    controls = descriptor["build"]["compile_meta"]
    variant = int(controls["kernel_variant"])
    if variant not in VARIANT_KERNELS:
        raise RunnerBlocked(f"RUNNER_BLOCKED: variant {variant} is not a full transpose")
    dims = descriptor["launch"]["grid_dims"]
    rows, cols = dims["rows"], dims["cols"]
    in_arr = deterministic_inputs(rows, cols)
    in_path, o_path = workdir / "in.bin", workdir / "out.bin"
    with open(in_path, "wb") as f:
        in_arr.tofile(f)
    proc = subprocess.run(
        [str(binary), str(cols), str(rows), str(variant), str(in_path), str(o_path)],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        raise RunnerBlocked(f"RUNNER_BLOCKED: harness run failed: {proc.stderr[-2000:]}")
    out = array.array("f")
    with open(o_path, "rb") as f:
        out.fromfile(f, rows * cols)
    # Transpose is a permutation: exact per-element equality is required and expected.
    if not cuda_transpose_output_matches(rows, cols, list(out), list(in_arr)):
        raise RuntimeError("CORRUPT_OUTPUT_REJECTED: transpose output mismatches reference")
    # Status reflects coordinator-accepted GPU validation 2026-09-19 (12/12 cells).
    # Do not revert without coordinator direction.
    result = {
        "status": "compiled_gpu_verified",
        "source_revision": revision,
        "source_sha256": actual_hash,
        "source_path": SOURCE_REL,
        "regime": regime,
        "candidate_id": candidate_id,
        "rows": rows,
        "cols": cols,
        "controls": {"kernel_variant": variant,
                     "kernel_name": VARIANT_KERNELS[variant],
                     "threads_per_block": 512},
        "build": {"nvcc": nvcc, "arch": build_arch(),
                  "defines": ["main=transpose_sample_main_disabled"],
                  "note": "pinned bytes unmodified; sample main renamed at compile time only"},
        "reference": {"elements_checked": rows * cols, "exact_match": True},
        "runtime": {
            "python": platform.python_version(),
        },
    }
    return result


def prepare_binary_energy_context(source_root: Path, regime: str, candidate_id: str, workdir: Path):
    """Build once, return a BinaryEnergyContext for energy_harness/application_energy_harness.py.
    Mirrors run_candidate()'s setup exactly; does not invoke the binary itself."""
    hpc_dir = Path(__file__).resolve().parents[2] / "energy_harness"
    if str(hpc_dir) not in sys.path:
        sys.path.insert(0, str(hpc_dir))
    from application_energy_harness import BinaryEnergyContext

    from transpose_adapter import cell_descriptor
    from correctness_reference import cuda_transpose_output_matches

    source_file, revision = verify_source(source_root)
    actual_hash = sha256_file(source_file)
    descriptor = cell_descriptor(regime, candidate_id)
    nvcc = find_nvcc()
    binary = build_binary(source_root, workdir, nvcc)
    controls = descriptor["build"]["compile_meta"]
    variant = int(controls["kernel_variant"])
    if variant not in VARIANT_KERNELS:
        raise RunnerBlocked(f"RUNNER_BLOCKED: variant {variant} is not a full transpose")
    dims = descriptor["launch"]["grid_dims"]
    rows, cols = dims["rows"], dims["cols"]
    in_arr = deterministic_inputs(rows, cols)
    in_path, o_path = workdir / "in.bin", workdir / "out.bin"
    with open(in_path, "wb") as f:
        in_arr.tofile(f)

    def check():
        out = array.array("f")
        with open(o_path, "rb") as f:
            out.fromfile(f, rows * cols)
        return cuda_transpose_output_matches(rows, cols, list(out), list(in_arr))

    return BinaryEnergyContext(
        parent_id="train_cuda_samples_transpose", regime=regime, candidate_id=candidate_id,
        source_revision=revision, source_sha256=actual_hash, source_path=SOURCE_REL,
        controls={"kernel_variant": variant, "kernel_name": VARIANT_KERNELS[variant],
                  "threads_per_block": 512},
        runtime_info={"python": platform.python_version(), "nvcc": nvcc, "arch": build_arch()},
        binary=binary, argv_prefix=[str(cols), str(rows), str(variant), str(in_path), str(o_path)],
        check=check,
    )


def self_test() -> None:
    from transpose_adapter import cell_descriptor

    with tempfile.TemporaryDirectory() as temp:
        fixture = Path(temp) / "source.py"
        fixture.write_bytes(b"pinned fixture")
        expected = sha256_file(fixture)
        assert sha256_file(fixture) == expected
        fixture.write_bytes(b"corrupt fixture")
        assert sha256_file(fixture) != expected
    assert "DRIVER_TEMPLATE" in globals() and "<<<grid, threads, 0, stream>>>" in DRIVER_TEMPLATE
    assert "int main(int argc" in DRIVER_TEMPLATE  # driver owns main; sample main renamed at build
    assert "-Dmain=" not in DRIVER_TEMPLATE  # the define lives in build_binary, documented there
    for bad_variant in (0, 1, 5, 6, 8):
        assert bad_variant not in VARIANT_KERNELS
    for regime in ("small", "medium", "large"):
        for candidate in ("c1", "c2", "c3", "c4"):
            d = cell_descriptor(regime, candidate)
            assert d["source_status"] == "source_verified"
            assert d["implementation_status"] == "compiled_gpu_verified"
            assert d["semantics"]["same_problem_across_candidates"]
    from correctness_reference import cuda_transpose_output_matches, ref_cuda_transpose
    assert cuda_transpose_output_matches(8, 8, ref_cuda_transpose(8, 8), None)
    bad = ref_cuda_transpose(8, 8)
    bad[3] += 1.0
    assert not cuda_transpose_output_matches(8, 8, bad, None)
    assert not cuda_transpose_output_matches(8, 8, ref_cuda_transpose(8, 8)[:-1], None)
    assert not cuda_transpose_output_matches(8, 8, [float("nan")] * 64, None)
    print("CPU_ONLY_TRANSPOSE_RUNNER_OK: hash/reference/candidate/corruption checks passed")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", type=Path)
    parser.add_argument("--regime", choices=("small", "medium", "large"))
    parser.add_argument("--candidate", choices=("c1", "c2", "c3", "c4"))
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--workdir", type=Path, default=None)
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return 0
    if args.source_root is None or args.regime is None or args.candidate is None:
        parser.error("--source-root, --regime, and --candidate are required unless --self-test")
    try:
        with tempfile.TemporaryDirectory(prefix="transpose_harness_") as temp:
            workdir = args.workdir or Path(temp)
            workdir.mkdir(parents=True, exist_ok=True)
            print(json.dumps(run_candidate(args.source_root, args.regime, args.candidate, workdir),
                             sort_keys=True))
    except RunnerBlocked as exc:
        print(str(exc), file=sys.stderr)
        return 3
    return 0


if __name__ == "__main__":
    main()
