
// Harness driver for the pinned vectorAdd sample kernel (generated by copy_runner.py).
// Owns main(), deterministic inputs, launch geometry, and result dump. The compute
// kernel itself is linked from the pinned, byte-unmodified vectorAdd.cu object.
//
// Optional energy-measurement mode (--repeat/--graph-batch/--trace-dir, all three
// required together): captures graph_batch launches into one CUDA graph on a private
// stream and replays it, mirroring Task B's fixtures and Task C's Python-callable
// runners' torch.cuda.CUDAGraph path (M311) -- a plain host-enqueue loop was found to
// spend 53-87% of its window on launch submission for microbenchmark-scale kernels
// (M310), so this driver captures a graph from the start. With no --repeat, the
// single-shot correctness path below is byte-for-byte unchanged.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cuda_runtime.h>

__global__ void vecAdd(float *A, float *B, float *C, int vectorLength);

#define CUDA_CHECK(call) do { cudaError_t s_ = (call); \
    if (s_ != cudaSuccess) { std::fprintf(stderr, "FATAL CUDA %s:%d: %s\n", \
    __FILE__, __LINE__, cudaGetErrorString(s_)); std::exit(2); } } while (0)

static long long monotonic_ns() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000000000LL + ts.tv_nsec;
}

int main(int argc, char **argv) {
    if (argc != 6 && argc != 12) {
        std::fprintf(stderr, "usage: %s <n> <threads> <x.bin> <y.bin> <out.bin> "
                     "[--repeat N --graph-batch B --trace-dir DIR]\n", argv[0]);
        return 2;
    }
    const int n = std::atoi(argv[1]);
    const int threads = std::atoi(argv[2]);
    if (n <= 0 || threads <= 0) { std::fprintf(stderr, "FATAL: bad geometry\n"); return 2; }
    FILE *fx = std::fopen(argv[3], "rb");
    FILE *fy = std::fopen(argv[4], "rb");
    if (!fx || !fy) { std::fprintf(stderr, "FATAL: cannot open inputs\n"); return 2; }
    float *h_x = (float *)std::malloc((size_t)n * sizeof(float));
    float *h_y = (float *)std::malloc((size_t)n * sizeof(float));
    float *h_o = (float *)std::malloc((size_t)n * sizeof(float));
    if (!h_x || !h_y || !h_o) { std::fprintf(stderr, "FATAL: host alloc\n"); return 2; }
    if (std::fread(h_x, sizeof(float), n, fx) != (size_t)n ||
        std::fread(h_y, sizeof(float), n, fy) != (size_t)n) {
        std::fprintf(stderr, "FATAL: short input read\n"); return 2;
    }
    std::fclose(fx); std::fclose(fy);
    float *d_x, *d_y, *d_o;
    CUDA_CHECK(cudaMalloc(&d_x, (size_t)n * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_y, (size_t)n * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_o, (size_t)n * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_x, h_x, (size_t)n * sizeof(float), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_y, h_y, (size_t)n * sizeof(float), cudaMemcpyHostToDevice));
    const int blocks = (n + threads - 1) / threads;

    long long repeat = 0, graph_batch = 0;
    const char *trace_dir = nullptr;
    if (argc == 12) {
        if (std::strcmp(argv[6], "--repeat") != 0 || std::strcmp(argv[8], "--graph-batch") != 0 ||
            std::strcmp(argv[10], "--trace-dir") != 0) {
            std::fprintf(stderr, "FATAL: expected --repeat N --graph-batch B --trace-dir DIR\n");
            return 2;
        }
        repeat = std::atoll(argv[7]);
        graph_batch = std::atoll(argv[9]);
        trace_dir = argv[11];
        if (repeat <= 0 || graph_batch <= 0) { std::fprintf(stderr, "FATAL: bad repeat/graph-batch\n"); return 2; }
    }

    if (trace_dir == nullptr) {
        vecAdd<<<blocks, threads>>>(d_x, d_y, d_o, n);
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaDeviceSynchronize());
    } else {
        cudaStream_t stream;
        CUDA_CHECK(cudaStreamCreate(&stream));
        cudaGraph_t graph;
        cudaGraphExec_t graph_exec;
        CUDA_CHECK(cudaStreamBeginCapture(stream, cudaStreamCaptureModeGlobal));
        for (long long i = 0; i < graph_batch; ++i) {
            vecAdd<<<blocks, threads, 0, stream>>>(d_x, d_y, d_o, n);
        }
        CUDA_CHECK(cudaStreamEndCapture(stream, &graph));
        CUDA_CHECK(cudaGraphInstantiate(&graph_exec, graph, nullptr, nullptr, 0));
        CUDA_CHECK(cudaGraphLaunch(graph_exec, stream));  // warm-up, discarded
        CUDA_CHECK(cudaStreamSynchronize(stream));

        cudaEvent_t ev_begin, ev_end;
        CUDA_CHECK(cudaEventCreate(&ev_begin));
        CUDA_CHECK(cudaEventCreate(&ev_end));
        const long long full_replays = repeat / graph_batch;
        const long long remainder = repeat % graph_batch;
        const long long host_begin_ns = monotonic_ns();
        CUDA_CHECK(cudaEventRecord(ev_begin, stream));
        for (long long r = 0; r < full_replays; ++r) {
            CUDA_CHECK(cudaGraphLaunch(graph_exec, stream));
        }
        for (long long i = 0; i < remainder; ++i) {
            vecAdd<<<blocks, threads, 0, stream>>>(d_x, d_y, d_o, n);
        }
        CUDA_CHECK(cudaEventRecord(ev_end, stream));
        CUDA_CHECK(cudaEventSynchronize(ev_end));
        const long long host_end_ns = monotonic_ns();
        float elapsed_ms = 0.0f;
        CUDA_CHECK(cudaEventElapsedTime(&elapsed_ms, ev_begin, ev_end));

        char windows_path[4096];
        std::snprintf(windows_path, sizeof(windows_path), "%s/windows.csv", trace_dir);
        FILE *fw = std::fopen(windows_path, "w");
        if (!fw) { std::fprintf(stderr, "FATAL: cannot open windows.csv\n"); return 2; }
        std::fprintf(fw, "block,launches,host_begin_monotonic_ns,host_end_monotonic_ns,cuda_seconds\n");
        std::fprintf(fw, "1,%lld,%lld,%lld,%.9f\n", repeat, host_begin_ns, host_end_ns,
                     (double)elapsed_ms / 1000.0);
        std::fclose(fw);

        CUDA_CHECK(cudaGraphExecDestroy(graph_exec));
        CUDA_CHECK(cudaGraphDestroy(graph));
        CUDA_CHECK(cudaStreamDestroy(stream));
    }

    CUDA_CHECK(cudaMemcpy(h_o, d_o, (size_t)n * sizeof(float), cudaMemcpyDeviceToHost));
    FILE *fo = std::fopen(argv[5], "wb");
    if (!fo) { std::fprintf(stderr, "FATAL: cannot open output\n"); return 2; }
    if (std::fwrite(h_o, sizeof(float), n, fo) != (size_t)n) {
        std::fprintf(stderr, "FATAL: short output write\n"); return 2;
    }
    std::fclose(fo);
    std::printf("COPY_DONE n=%d threads=%d blocks=%d\n", n, threads, blocks);
    return 0;
}
