
// Harness driver for the pinned CUDA Samples transpose.cu tile kernels used by the unseen-operator parents
// (generated by tile_family.py).  Owns main(), the input, the sample-native launch geometry and the result dump.
// The kernels are linked from the pinned, byte-unmodified transpose.cu object (sample main renamed at build).
// Variant numbers follow the sample: 0 copy, 1 copySharedMem, 5 transposeCoarseGrained, 6 transposeFineGrained.
//
// Optional energy-measurement mode (--repeat/--graph-batch/--trace-dir, all three required together):
// captures graph_batch launches into one CUDA graph on a private stream and replays it (same design as the
// existing transpose/copy/reduction drivers).  With no --repeat this is a single-shot correctness run.
// The output buffer is memset to 0xFF (NaN) before any launch so unwritten elements are detectable.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cuda_runtime.h>

__global__ void copy(float *odata, float *idata, int width, int height);
__global__ void copySharedMem(float *odata, float *idata, int width, int height);
__global__ void transposeCoarseGrained(float *odata, float *idata, int width, int height);
__global__ void transposeFineGrained(float *odata, float *idata, int width, int height);

#define CUDA_CHECK(call) do { cudaError_t s_ = (call); \
    if (s_ != cudaSuccess) { std::fprintf(stderr, "FATAL CUDA %s:%d: %s\n", \
    __FILE__, __LINE__, cudaGetErrorString(s_)); std::exit(2); } } while (0)

static long long monotonic_ns() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000000000LL + ts.tv_nsec;
}

static bool launch_variant(int variant, dim3 grid, dim3 threads, cudaStream_t stream,
                           float *d_out, float *d_in, int dim_x, int dim_y) {
    switch (variant) {
        case 0: copy<<<grid, threads, 0, stream>>>(d_out, d_in, dim_x, dim_y); return true;
        case 1: copySharedMem<<<grid, threads, 0, stream>>>(d_out, d_in, dim_x, dim_y); return true;
        case 5: transposeCoarseGrained<<<grid, threads, 0, stream>>>(d_out, d_in, dim_x, dim_y); return true;
        case 6: transposeFineGrained<<<grid, threads, 0, stream>>>(d_out, d_in, dim_x, dim_y); return true;
        default: return false;
    }
}

int main(int argc, char **argv) {
    if (argc != 6 && argc != 12) {
        std::fprintf(stderr, "usage: %s <dim_x> <dim_y> <variant> <in.bin> <out.bin> "
                     "[--repeat N --graph-batch B --trace-dir DIR]\n", argv[0]);
        return 2;
    }
    const int dim_x = std::atoi(argv[1]);
    const int dim_y = std::atoi(argv[2]);
    const int variant = std::atoi(argv[3]);
    if (dim_x <= 0 || dim_y <= 0) { std::fprintf(stderr, "FATAL: bad dims\n"); return 2; }
    if (dim_x % 32 != 0 || dim_y % 32 != 0) {
        std::fprintf(stderr, "FATAL: dims must be multiples of TILE_DIM=32\n"); return 2;
    }
    const size_t n = (size_t)dim_x * (size_t)dim_y;
    FILE *fi = std::fopen(argv[4], "rb");
    if (!fi) { std::fprintf(stderr, "FATAL: cannot open input\n"); return 2; }
    float *h_in = (float *)std::malloc(n * sizeof(float));
    float *h_out = (float *)std::malloc(n * sizeof(float));
    if (!h_in || !h_out) { std::fprintf(stderr, "FATAL: host alloc\n"); return 2; }
    if (std::fread(h_in, sizeof(float), n, fi) != n) {
        std::fprintf(stderr, "FATAL: short input read\n"); return 2;
    }
    std::fclose(fi);
    float *d_in, *d_out;
    CUDA_CHECK(cudaMalloc(&d_in, n * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, n * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, n * sizeof(float), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemset(d_out, 0xFF, n * sizeof(float)));  // NaN sentinel: an unwritten element stays NaN
    CUDA_CHECK(cudaDeviceSynchronize());
    // Sample-native launch: grid covers dim/32 tiles per axis, (32,16) blocks (BLOCK_ROWS is hard-coded to 16).
    dim3 grid(dim_x / 32, dim_y / 32, 1);
    dim3 threads(32, 16, 1);

    long long repeat = 0, graph_batch = 0;
    const char *trace_dir = nullptr;
    if (argc == 12) {
        if (std::strcmp(argv[6], "--repeat") != 0 || std::strcmp(argv[8], "--graph-batch") != 0 ||
            std::strcmp(argv[10], "--trace-dir") != 0) {
            std::fprintf(stderr, "FATAL: expected --repeat N --graph-batch B --trace-dir DIR\n");
            return 2;
        }
        repeat = std::atoll(argv[7]);
        graph_batch = std::atoll(argv[9]);
        trace_dir = argv[11];
        if (repeat <= 0 || graph_batch <= 0) { std::fprintf(stderr, "FATAL: bad repeat/graph-batch\n"); return 2; }
    }

    if (trace_dir == nullptr) {
        if (!launch_variant(variant, grid, threads, 0, d_out, d_in, dim_x, dim_y)) {
            std::fprintf(stderr, "FATAL: unsupported variant %d\n", variant); return 2;
        }
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaDeviceSynchronize());
    } else {
        cudaStream_t stream;
        CUDA_CHECK(cudaStreamCreate(&stream));
        if (!launch_variant(variant, grid, threads, stream, d_out, d_in, dim_x, dim_y)) {
            std::fprintf(stderr, "FATAL: unsupported variant %d\n", variant); return 2;
        }
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaStreamSynchronize(stream));  // probe launch above, discarded; also validates variant

        cudaGraph_t graph;
        cudaGraphExec_t graph_exec;
        CUDA_CHECK(cudaStreamBeginCapture(stream, cudaStreamCaptureModeGlobal));
        for (long long i = 0; i < graph_batch; ++i) {
            launch_variant(variant, grid, threads, stream, d_out, d_in, dim_x, dim_y);
        }
        CUDA_CHECK(cudaStreamEndCapture(stream, &graph));
        CUDA_CHECK(cudaGraphInstantiate(&graph_exec, graph, nullptr, nullptr, 0));
        CUDA_CHECK(cudaGraphLaunch(graph_exec, stream));  // warm-up, discarded
        CUDA_CHECK(cudaStreamSynchronize(stream));

        cudaEvent_t ev_begin, ev_end;
        CUDA_CHECK(cudaEventCreate(&ev_begin));
        CUDA_CHECK(cudaEventCreate(&ev_end));
        const long long full_replays = repeat / graph_batch;
        const long long remainder = repeat % graph_batch;
        const long long host_begin_ns = monotonic_ns();
        CUDA_CHECK(cudaEventRecord(ev_begin, stream));
        for (long long r = 0; r < full_replays; ++r) {
            CUDA_CHECK(cudaGraphLaunch(graph_exec, stream));
        }
        for (long long i = 0; i < remainder; ++i) {
            launch_variant(variant, grid, threads, stream, d_out, d_in, dim_x, dim_y);
        }
        CUDA_CHECK(cudaEventRecord(ev_end, stream));
        CUDA_CHECK(cudaEventSynchronize(ev_end));
        const long long host_end_ns = monotonic_ns();
        float elapsed_ms = 0.0f;
        CUDA_CHECK(cudaEventElapsedTime(&elapsed_ms, ev_begin, ev_end));

        char windows_path[4096];
        std::snprintf(windows_path, sizeof(windows_path), "%s/windows.csv", trace_dir);
        FILE *fw = std::fopen(windows_path, "w");
        if (!fw) { std::fprintf(stderr, "FATAL: cannot open windows.csv\n"); return 2; }
        std::fprintf(fw, "block,launches,host_begin_monotonic_ns,host_end_monotonic_ns,cuda_seconds\n");
        std::fprintf(fw, "1,%lld,%lld,%lld,%.9f\n", repeat, host_begin_ns, host_end_ns,
                     (double)elapsed_ms / 1000.0);
        std::fclose(fw);

        CUDA_CHECK(cudaGraphExecDestroy(graph_exec));
        CUDA_CHECK(cudaGraphDestroy(graph));
        CUDA_CHECK(cudaStreamDestroy(stream));
    }

    CUDA_CHECK(cudaMemcpy(h_out, d_out, n * sizeof(float), cudaMemcpyDeviceToHost));
    FILE *fo = std::fopen(argv[5], "wb");
    if (!fo) { std::fprintf(stderr, "FATAL: cannot open output\n"); return 2; }
    if (std::fwrite(h_out, sizeof(float), n, fo) != n) {
        std::fprintf(stderr, "FATAL: short output write\n"); return 2;
    }
    std::fclose(fo);
    std::printf("TILE_DONE dim=%dx%d variant=%d grid=%dx%d block=32x16 blocks=%d\n", dim_x, dim_y, variant,
                dim_x / 32, dim_y / 32, (dim_x / 32) * (dim_y / 32));
    return 0;
}
