#!/usr/bin/env python3
"""Shared harness for the two parents built from the pinned CUDA Samples ``transpose.cu``:
``alt_cuda_samples_copy`` (copy, copySharedMem) and ``alt_cuda_samples_transposefine``
(transposeFineGrained, transposeCoarseGrained).

Build model = the existing ``transpose_runner.py``: the pinned ``transpose.cu`` is compiled with
``-Dmain=transpose_sample_main_disabled`` (bytes never modified) and linked with the driver below, which owns
``main``, the input, the sample-native launch geometry and native cudaGraph capture on a private stream.  Extra
driver behaviour relative to the existing transpose driver: the output buffer is filled with a NaN sentinel
(``cudaMemset 0xFF``) before any launch, so an element a kernel never writes is detected instead of reading back
as leftover memory; and the driver echoes the launched grid and block shape.

Launch geometry is fixed by the kernels, not chosen: they step their tile loops by the hard-coded BLOCK_ROWS = 16,
so a block is (32, 16) = 512 threads and the grid is (dim_x / 32, dim_y / 32).  The manifest's "256 threads per
block" does not apply to these kernels (a 256-thread block would cover half of each 32-row tile); the runner
records the actual shape in ``controls``.

Oracles (see HANDOFF.md, "Open decision: what 'correct' means for the partial kernels"):
  copy family, ``identity``: output words bitwise equal to the input words (the freeze's oracle).
  transposefine, ``kernel_semantics`` (default, the freeze's oracle): the exact permutation each partial kernel
  performs, read from the pinned source (fine-grained: transpose inside each tile, tile left in place;
  coarse-grained: tile moved, no transpose inside it).  Verified on Blackwell GPU 1 on all 6 cells: each kernel's
  real output equals its own permutation on every element (CHANGELOG M411).
  transposefine, ``full_transpose`` (explicit opt-in via UNSEEN_TRANSPOSEFINE_ORACLE, diagnostic only): out[r][c] ==
  in[c][r]; neither kernel can pass it.  The oracle actually used is recorded in ``controls``/the result.
Correctness-only mode always evaluates every oracle and reports the results as diagnostics.
"""
from __future__ import annotations

import array
import json
import math
import os
import platform
import random
import subprocess
import sys
from pathlib import Path

import unseen_common as uc
from unseen_common import RunnerBlocked, UnseenOperatorConfigError

TILE_DIM = 32
BLOCK_ROWS = 16
THREADS_PER_BLOCK = TILE_DIM * BLOCK_ROWS  # (32, 16)
SENTINEL_WORD = 0xFFFFFFFF                 # NaN bit pattern the driver memsets into the output
TRANSPOSE_INPUT_MODULUS = 1 << 24          # float32 holds every integer below 2**24 exactly
ORACLE_ENV = "UNSEEN_TRANSPOSEFINE_ORACLE"
TRANSPOSEFINE_ORACLES = ("full_transpose", "kernel_semantics")
COPY_PARENT = "alt_cuda_samples_copy"
TRANSPOSEFINE_PARENT = "alt_cuda_samples_transposefine"
KERNEL_NAMES = ("copy", "copySharedMem", "transposeCoarseGrained", "transposeFineGrained")

DRIVER_TEMPLATE = r"""
// Harness driver for the pinned CUDA Samples transpose.cu tile kernels used by the unseen-operator parents
// (generated by tile_family.py).  Owns main(), the input, the sample-native launch geometry and the result dump.
// The kernels are linked from the pinned, byte-unmodified transpose.cu object (sample main renamed at build).
// Variant numbers follow the sample: 0 copy, 1 copySharedMem, 5 transposeCoarseGrained, 6 transposeFineGrained.
//
// Optional energy-measurement mode (--repeat/--graph-batch/--trace-dir, all three required together):
// captures graph_batch launches into one CUDA graph on a private stream and replays it (same design as the
// existing transpose/copy/reduction drivers).  With no --repeat this is a single-shot correctness run.
// The output buffer is memset to 0xFF (NaN) before any launch so unwritten elements are detectable.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cuda_runtime.h>

__global__ void copy(float *odata, float *idata, int width, int height);
__global__ void copySharedMem(float *odata, float *idata, int width, int height);
__global__ void transposeCoarseGrained(float *odata, float *idata, int width, int height);
__global__ void transposeFineGrained(float *odata, float *idata, int width, int height);

#define CUDA_CHECK(call) do { cudaError_t s_ = (call); \
    if (s_ != cudaSuccess) { std::fprintf(stderr, "FATAL CUDA %s:%d: %s\n", \
    __FILE__, __LINE__, cudaGetErrorString(s_)); std::exit(2); } } while (0)

static long long monotonic_ns() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000000000LL + ts.tv_nsec;
}

static bool launch_variant(int variant, dim3 grid, dim3 threads, cudaStream_t stream,
                           float *d_out, float *d_in, int dim_x, int dim_y) {
    switch (variant) {
        case 0: copy<<<grid, threads, 0, stream>>>(d_out, d_in, dim_x, dim_y); return true;
        case 1: copySharedMem<<<grid, threads, 0, stream>>>(d_out, d_in, dim_x, dim_y); return true;
        case 5: transposeCoarseGrained<<<grid, threads, 0, stream>>>(d_out, d_in, dim_x, dim_y); return true;
        case 6: transposeFineGrained<<<grid, threads, 0, stream>>>(d_out, d_in, dim_x, dim_y); return true;
        default: return false;
    }
}

int main(int argc, char **argv) {
    if (argc != 6 && argc != 12) {
        std::fprintf(stderr, "usage: %s <dim_x> <dim_y> <variant> <in.bin> <out.bin> "
                     "[--repeat N --graph-batch B --trace-dir DIR]\n", argv[0]);
        return 2;
    }
    const int dim_x = std::atoi(argv[1]);
    const int dim_y = std::atoi(argv[2]);
    const int variant = std::atoi(argv[3]);
    if (dim_x <= 0 || dim_y <= 0) { std::fprintf(stderr, "FATAL: bad dims\n"); return 2; }
    if (dim_x % 32 != 0 || dim_y % 32 != 0) {
        std::fprintf(stderr, "FATAL: dims must be multiples of TILE_DIM=32\n"); return 2;
    }
    const size_t n = (size_t)dim_x * (size_t)dim_y;
    FILE *fi = std::fopen(argv[4], "rb");
    if (!fi) { std::fprintf(stderr, "FATAL: cannot open input\n"); return 2; }
    float *h_in = (float *)std::malloc(n * sizeof(float));
    float *h_out = (float *)std::malloc(n * sizeof(float));
    if (!h_in || !h_out) { std::fprintf(stderr, "FATAL: host alloc\n"); return 2; }
    if (std::fread(h_in, sizeof(float), n, fi) != n) {
        std::fprintf(stderr, "FATAL: short input read\n"); return 2;
    }
    std::fclose(fi);
    float *d_in, *d_out;
    CUDA_CHECK(cudaMalloc(&d_in, n * sizeof(float)));
    CUDA_CHECK(cudaMalloc(&d_out, n * sizeof(float)));
    CUDA_CHECK(cudaMemcpy(d_in, h_in, n * sizeof(float), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemset(d_out, 0xFF, n * sizeof(float)));  // NaN sentinel: an unwritten element stays NaN
    CUDA_CHECK(cudaDeviceSynchronize());
    // Sample-native launch: grid covers dim/32 tiles per axis, (32,16) blocks (BLOCK_ROWS is hard-coded to 16).
    dim3 grid(dim_x / 32, dim_y / 32, 1);
    dim3 threads(32, 16, 1);

    long long repeat = 0, graph_batch = 0;
    const char *trace_dir = nullptr;
    if (argc == 12) {
        if (std::strcmp(argv[6], "--repeat") != 0 || std::strcmp(argv[8], "--graph-batch") != 0 ||
            std::strcmp(argv[10], "--trace-dir") != 0) {
            std::fprintf(stderr, "FATAL: expected --repeat N --graph-batch B --trace-dir DIR\n");
            return 2;
        }
        repeat = std::atoll(argv[7]);
        graph_batch = std::atoll(argv[9]);
        trace_dir = argv[11];
        if (repeat <= 0 || graph_batch <= 0) { std::fprintf(stderr, "FATAL: bad repeat/graph-batch\n"); return 2; }
    }

    if (trace_dir == nullptr) {
        if (!launch_variant(variant, grid, threads, 0, d_out, d_in, dim_x, dim_y)) {
            std::fprintf(stderr, "FATAL: unsupported variant %d\n", variant); return 2;
        }
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaDeviceSynchronize());
    } else {
        cudaStream_t stream;
        CUDA_CHECK(cudaStreamCreate(&stream));
        if (!launch_variant(variant, grid, threads, stream, d_out, d_in, dim_x, dim_y)) {
            std::fprintf(stderr, "FATAL: unsupported variant %d\n", variant); return 2;
        }
        CUDA_CHECK(cudaGetLastError());
        CUDA_CHECK(cudaStreamSynchronize(stream));  // probe launch above, discarded; also validates variant

        cudaGraph_t graph;
        cudaGraphExec_t graph_exec;
        CUDA_CHECK(cudaStreamBeginCapture(stream, cudaStreamCaptureModeGlobal));
        for (long long i = 0; i < graph_batch; ++i) {
            launch_variant(variant, grid, threads, stream, d_out, d_in, dim_x, dim_y);
        }
        CUDA_CHECK(cudaStreamEndCapture(stream, &graph));
        CUDA_CHECK(cudaGraphInstantiate(&graph_exec, graph, nullptr, nullptr, 0));
        CUDA_CHECK(cudaGraphLaunch(graph_exec, stream));  // warm-up, discarded
        CUDA_CHECK(cudaStreamSynchronize(stream));

        cudaEvent_t ev_begin, ev_end;
        CUDA_CHECK(cudaEventCreate(&ev_begin));
        CUDA_CHECK(cudaEventCreate(&ev_end));
        const long long full_replays = repeat / graph_batch;
        const long long remainder = repeat % graph_batch;
        const long long host_begin_ns = monotonic_ns();
        CUDA_CHECK(cudaEventRecord(ev_begin, stream));
        for (long long r = 0; r < full_replays; ++r) {
            CUDA_CHECK(cudaGraphLaunch(graph_exec, stream));
        }
        for (long long i = 0; i < remainder; ++i) {
            launch_variant(variant, grid, threads, stream, d_out, d_in, dim_x, dim_y);
        }
        CUDA_CHECK(cudaEventRecord(ev_end, stream));
        CUDA_CHECK(cudaEventSynchronize(ev_end));
        const long long host_end_ns = monotonic_ns();
        float elapsed_ms = 0.0f;
        CUDA_CHECK(cudaEventElapsedTime(&elapsed_ms, ev_begin, ev_end));

        char windows_path[4096];
        std::snprintf(windows_path, sizeof(windows_path), "%s/windows.csv", trace_dir);
        FILE *fw = std::fopen(windows_path, "w");
        if (!fw) { std::fprintf(stderr, "FATAL: cannot open windows.csv\n"); return 2; }
        std::fprintf(fw, "block,launches,host_begin_monotonic_ns,host_end_monotonic_ns,cuda_seconds\n");
        std::fprintf(fw, "1,%lld,%lld,%lld,%.9f\n", repeat, host_begin_ns, host_end_ns,
                     (double)elapsed_ms / 1000.0);
        std::fclose(fw);

        CUDA_CHECK(cudaGraphExecDestroy(graph_exec));
        CUDA_CHECK(cudaGraphDestroy(graph));
        CUDA_CHECK(cudaStreamDestroy(stream));
    }

    CUDA_CHECK(cudaMemcpy(h_out, d_out, n * sizeof(float), cudaMemcpyDeviceToHost));
    FILE *fo = std::fopen(argv[5], "wb");
    if (!fo) { std::fprintf(stderr, "FATAL: cannot open output\n"); return 2; }
    if (std::fwrite(h_out, sizeof(float), n, fo) != n) {
        std::fprintf(stderr, "FATAL: short output write\n"); return 2;
    }
    std::fclose(fo);
    std::printf("TILE_DONE dim=%dx%d variant=%d grid=%dx%d block=32x16 blocks=%d\n", dim_x, dim_y, variant,
                dim_x / 32, dim_y / 32, (dim_x / 32) * (dim_y / 32));
    return 0;
}
"""

_BUILD_CACHE: dict = {}


# ---------------------------------------------------------------------------- geometry
def tile_dims(parent_id: str, n: int) -> tuple[int, int]:
    """(dim_x = width, dim_y = height).  Transpose cells are n x n.  Copy cells hold n elements: a square when n is
    one, otherwise the widest power-of-two rectangle with width >= height.  The frozen copy cells are all square: the
    pinned copySharedMem write guard swaps width and height, so it writes only half of a non-square output
    (measured on Blackwell, CHANGELOG M411).  The freeze's byte formula 2*4*n holds for any shape."""
    if parent_id == TRANSPOSEFINE_PARENT:
        dims = (n, n)
    elif parent_id == COPY_PARENT:
        side = math.isqrt(n)
        if side * side == n:
            dims = (side, side)
        elif n & (n - 1) == 0:
            width = 1 << ((n.bit_length() - 1 + 1) // 2)
            dims = (width, n // width)
        else:
            raise UnseenOperatorConfigError(f"copy element count {n} is neither a square nor a power of two")
    else:
        raise UnseenOperatorConfigError(f"unknown tile-family parent {parent_id!r}")
    if dims[0] % TILE_DIM or dims[1] % TILE_DIM or dims[0] * dims[1] != (n * n if parent_id == TRANSPOSEFINE_PARENT else n):
        raise UnseenOperatorConfigError(f"{parent_id}: dims {dims} for n={n} are not a multiple-of-{TILE_DIM} factorisation")
    return dims


def selected_oracle(parent_id: str, environ=None) -> str:
    environ = os.environ if environ is None else environ
    if parent_id == COPY_PARENT:
        return "identity"
    value = environ.get(ORACLE_ENV, "").strip() or "kernel_semantics"
    if value not in TRANSPOSEFINE_ORACLES:
        raise RunnerBlocked(f"RUNNER_BLOCKED: {ORACLE_ENV}={value!r}; allowed: {', '.join(TRANSPOSEFINE_ORACLES)}")
    return value


def cell_plan(parent_id: str, regime: str, candidate_id: str, environ=None) -> dict:
    cell = uc.cell_config(parent_id, regime, candidate_id)
    dim_x, dim_y = tile_dims(parent_id, cell["n"])
    grid_x, grid_y = dim_x // TILE_DIM, dim_y // TILE_DIM
    oracle = selected_oracle(parent_id, environ)
    return {**cell, "dim_x": dim_x, "dim_y": dim_y, "grid_x": grid_x, "grid_y": grid_y, "blocks": grid_x * grid_y,
            "threads_per_block": THREADS_PER_BLOCK, "block_shape": [TILE_DIM, BLOCK_ROWS],
            "variant": cell["selector"], "elements": dim_x * dim_y, "bytes_model": uc.tile_bytes(dim_x, dim_y),
            "bytes_model_formula": "2*4*elements (every element read once and written once, float32)",
            "oracle": oracle}


# ---------------------------------------------------------------------------- inputs
def copy_input(count: int) -> array.array:
    """Seed-20260914 uniform(-1,1) float32 buffer (the existing copy runner's input convention)."""
    rng = random.Random(uc.SEED)
    return array.array("f", (rng.uniform(-1.0, 1.0) for _ in range(count)))


def transpose_input(count: int) -> array.array:
    """float(i % 2**24): every value exact in float32.  The existing transpose runner uses i % 8192, which repeats
    every 8192 elements and makes every row of an 8192 x 8192 input identical; this modulus keeps positions
    distinguishable (see HANDOFF.md, decision on input data)."""
    modulus = TRANSPOSE_INPUT_MODULUS
    block = array.array("f", map(float, range(min(count, modulus))))
    if count <= modulus:
        return block
    full = block * (count // modulus)
    full.extend(block[:count % modulus])
    return full


def build_input(parent_id: str, count: int) -> array.array:
    return copy_input(count) if parent_id == COPY_PARENT else transpose_input(count)


# ---------------------------------------------------------------------------- oracles (pure Python, row-wise)
def _bytes(a: array.array) -> bytes:
    return a.tobytes()


def _row(a: array.array, r: int, width: int) -> array.array:
    return a[r * width:(r + 1) * width]


def matches_identity(inp: array.array, out: array.array) -> bool:
    return len(inp) == len(out) and _bytes(inp) == _bytes(out)


def matches_full_transpose(inp: array.array, out: array.array, n: int) -> bool:
    """out[r][c] == in[c][r] for an n x n matrix.  Row r of the output is column r of the input."""
    if len(inp) != n * n or len(out) != n * n:
        return False
    return all(_bytes(inp[r::n]) == _bytes(_row(out, r, n)) for r in range(n))


def matches_fine_grained_partial(inp: array.array, out: array.array, n: int) -> bool:
    """transposeFineGrained on an n x n matrix: each 32 x 32 tile is transposed in place, tiles keep their position:
    out[32p + a][32q + b] == in[32p + b][32q + a]."""
    if len(inp) != n * n or len(out) != n * n or n % TILE_DIM:
        return False
    for p in range(n // TILE_DIM):
        src_rows = [_row(inp, p * TILE_DIM + b, n) for b in range(TILE_DIM)]
        for a in range(TILE_DIM):
            expected = array.array("f", bytes(4 * n))
            for b in range(TILE_DIM):
                expected[b::TILE_DIM] = src_rows[b][a::TILE_DIM]
            if _bytes(expected) != _bytes(_row(out, p * TILE_DIM + a, n)):
                return False
    return True


def matches_coarse_grained_partial(inp: array.array, out: array.array, n: int) -> bool:
    """transposeCoarseGrained on an n x n matrix: 32 x 32 tiles are moved to the transposed tile position but each
    tile's contents are not transposed: out[32p + r][32q + c] == in[32q + r][32p + c]."""
    if len(inp) != n * n or len(out) != n * n or n % TILE_DIM:
        return False
    tiles = n // TILE_DIM
    for p in range(tiles):
        for r in range(TILE_DIM):
            expected = array.array("f", bytes(4 * n))
            for q in range(tiles):
                start = (q * TILE_DIM + r) * n + p * TILE_DIM
                expected[q * TILE_DIM:(q + 1) * TILE_DIM] = inp[start:start + TILE_DIM]
            if _bytes(expected) != _bytes(_row(out, p * TILE_DIM + r, n)):
                return False
    return True


def matches_kernel_semantics(kernel_name: str, inp: array.array, out: array.array, n: int) -> bool:
    if kernel_name == "transposeFineGrained":
        return matches_fine_grained_partial(inp, out, n)
    if kernel_name == "transposeCoarseGrained":
        return matches_coarse_grained_partial(inp, out, n)
    raise UnseenOperatorConfigError(f"no partial-transpose semantics for {kernel_name!r}")


def oracle_passes(plan: dict, inp: array.array, out: array.array) -> bool:
    if plan["oracle"] == "identity":
        return matches_identity(inp, out)
    n = plan["dim_x"]
    if plan["oracle"] == "full_transpose":
        return matches_full_transpose(inp, out, n)
    return matches_kernel_semantics(plan["kernel_name"], inp, out, n)


def sentinel_stats(out_words: array.array, width: int) -> dict:
    """How much of the output the kernel never wrote (words still holding the driver's NaN sentinel)."""
    total = len(out_words)
    unwritten = out_words.count(SENTINEL_WORD)
    by_tile_row = {}
    if unwritten and width and total % width == 0:
        counts = [0] * TILE_DIM
        for r in range(total // width):
            if _row(out_words, r, width).count(SENTINEL_WORD):
                counts[r % TILE_DIM] += 1
        by_tile_row = {"rows_with_unwritten_by_row_mod_32": counts}
    return {"elements": total, "unwritten_elements": unwritten, "written_fraction": 1.0 - unwritten / total if total else 0.0,
            **by_tile_row}


def diagnostics(plan: dict, inp: array.array, out: array.array) -> dict:
    """Every oracle plus sentinel statistics; reported by the correctness-only mode, never used to pass a cell."""
    words = array.array("I")
    words.frombytes(_bytes(out))
    diag = {"sentinel": sentinel_stats(words, plan["dim_x"]), "matches_identity": matches_identity(inp, out)}
    if plan["parent_id"] == TRANSPOSEFINE_PARENT:
        n = plan["dim_x"]
        diag.update({
            "matches_full_transpose": matches_full_transpose(inp, out, n),
            "matches_fine_grained_partial": matches_fine_grained_partial(inp, out, n),
            "matches_coarse_grained_partial": matches_coarse_grained_partial(inp, out, n),
        })
    else:
        diag["identical_rows"] = sum(1 for r in range(plan["dim_y"])
                                     if _bytes(_row(inp, r, plan["dim_x"])) == _bytes(_row(out, r, plan["dim_x"])))
        diag["rows"] = plan["dim_y"]
    return diag


# ---------------------------------------------------------------------------- build, context, correctness-only
def build_binary(source_root: Path, workdir: Path, nvcc: str) -> Path:
    """Compile pinned transpose.cu (main renamed away) and link the driver.  Built once per (source, arch, workdir)."""
    key = (str(source_root), uc.build_arch(), str(workdir))
    if key in _BUILD_CACHE and _BUILD_CACHE[key].is_file():
        return _BUILD_CACHE[key]
    kernel_src, common_inc = source_root / uc.TRANSPOSE_REL, source_root / "Common"
    if not common_inc.is_dir():
        raise RunnerBlocked(f"RUNNER_BLOCKED: missing helper headers at {common_inc}")
    driver_src = workdir / "tile_family_driver.cu"
    driver_src.write_text(DRIVER_TEMPLATE, encoding="utf-8")
    kernel_obj, binary = workdir / "transpose_kernel.o", workdir / "tile_family_harness"
    arch = f"-arch={uc.build_arch()}"
    steps = [[nvcc, "-O2", arch, "-Dmain=transpose_sample_main_disabled", "-I", str(common_inc), "-c", str(kernel_src),
              "-o", str(kernel_obj)],
             [nvcc, "-O2", arch, str(driver_src), str(kernel_obj), "-o", str(binary)]]
    _BUILD_CACHE[key] = uc.run_nvcc_steps(steps, workdir, binary)
    return binary


def _prepare(parent_id: str, source_root: Path, regime: str, candidate_id: str, workdir: Path) -> dict:
    plan = cell_plan(parent_id, regime, candidate_id)
    uc.check_manifest_consistency()
    root, revision, hashes = uc.verify_source(source_root, (uc.TRANSPOSE_REL,))
    uc.check_four_arg_kernels(uc.read_source_text(root, uc.TRANSPOSE_REL), KERNEL_NAMES)
    nvcc = uc.find_nvcc()
    binary = build_binary(root, workdir, nvcc)
    inp = build_input(parent_id, plan["elements"])
    in_path, out_path = workdir / "in.bin", workdir / "out.bin"
    with open(in_path, "wb") as f:
        inp.tofile(f)
    return {"plan": plan, "root": root, "revision": revision, "hash": hashes[uc.TRANSPOSE_REL], "nvcc": nvcc,
            "binary": binary, "input": inp, "in_path": in_path, "out_path": out_path}


def _read_output(path: Path, count: int) -> array.array | None:
    out = array.array("f")
    try:
        with open(path, "rb") as f:
            out.fromfile(f, count)
    except (OSError, EOFError):
        return None
    return out if len(out) == count else None


def _argv_prefix(ctx: dict) -> list[str]:
    p = ctx["plan"]
    return [str(p["dim_x"]), str(p["dim_y"]), str(p["variant"]), str(ctx["in_path"]), str(ctx["out_path"])]


def _controls(plan: dict) -> dict:
    keys = ("kernel_name", "variant", "dim_x", "dim_y", "grid_x", "grid_y", "blocks", "threads_per_block", "block_shape",
            "elements", "bytes_model", "bytes_model_formula", "oracle", "manifest_threads_per_block")
    controls = {k: plan[k] for k in keys}
    controls["dtype"] = "float32"
    controls["input"] = ("seed 20260914 uniform(-1,1)" if plan["parent_id"] == COPY_PARENT
                         else f"float(i % {TRANSPOSE_INPUT_MODULUS})")
    return controls


def prepare_binary_energy_context(parent_id: str, source_root: Path, regime: str, candidate_id: str, workdir: Path):
    """Build once, return a BinaryEnergyContext for energy_harness/application_energy_harness.py (does not invoke the binary)."""
    ctx = _prepare(parent_id, source_root, regime, candidate_id, workdir)
    plan = ctx["plan"]

    def check() -> bool:
        out = _read_output(ctx["out_path"], plan["elements"])
        return out is not None and oracle_passes(plan, ctx["input"], out)

    return uc.import_binary_energy_context()(
        parent_id=parent_id, regime=regime, candidate_id=candidate_id, source_revision=ctx["revision"],
        source_sha256=ctx["hash"], source_path=uc.TRANSPOSE_REL, controls=_controls(plan),
        runtime_info={"python": platform.python_version(), "nvcc": ctx["nvcc"], "arch": uc.build_arch()},
        binary=ctx["binary"], argv_prefix=_argv_prefix(ctx), check=check)


def run_candidate(parent_id: str, source_root: Path, regime: str, candidate_id: str, workdir: Path) -> dict:
    """Correctness-only: one single-shot launch (no graph, no NVML, no energy window); every oracle reported."""
    ctx = _prepare(parent_id, source_root, regime, candidate_id, workdir)
    plan = ctx["plan"]
    proc = subprocess.run([str(ctx["binary"]), *_argv_prefix(ctx)], capture_output=True, text=True)
    if proc.returncode != 0:
        raise RunnerBlocked(f"RUNNER_BLOCKED: harness run failed: {proc.stderr[-2000:]}")
    out = _read_output(ctx["out_path"], plan["elements"])
    if out is None:
        raise RunnerBlocked("RUNNER_BLOCKED: output shape check failed")
    passed = oracle_passes(plan, ctx["input"], out)
    return {
        "status": "correctness_check_passed" if passed else "correctness_check_failed",
        "correctness_check": passed, "parent_id": parent_id, "runner": plan["runner"], "regime": regime,
        "candidate_id": candidate_id, "source_revision": ctx["revision"], "source_sha256": ctx["hash"],
        "source_path": uc.TRANSPOSE_REL, "controls": _controls(plan), "oracle_used": plan["oracle"],
        "diagnostics": diagnostics(plan, ctx["input"], out),
        "build": {"nvcc": ctx["nvcc"], "arch": uc.build_arch(), "defines": ["main=transpose_sample_main_disabled"]},
        "runtime": {"python": platform.python_version(), "driver_stdout": proc.stdout.strip()},
    }


def run_main(parent_id: str, description: str, self_test, argv=None) -> int:
    """Shared CLI for alt_copy_runner.py / alt_transposefine_runner.py."""
    import argparse
    import tempfile

    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("--source-root", type=Path)
    parser.add_argument("--regime", choices=uc.REGIME_ORDER)
    parser.add_argument("--candidate", choices=("c1", "c2"))
    parser.add_argument("--all-cells", action="store_true", help="run all 6 cells of this parent, one JSON line each")
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--workdir", type=Path, default=None)
    args = parser.parse_args(argv)
    if args.self_test:
        self_test()
        return 0
    if args.source_root is None or (not args.all_cells and (args.regime is None or args.candidate is None)):
        parser.error("--source-root and (--regime and --candidate, or --all-cells) are required unless --self-test")
    cells = ([(c["regime"], c["candidate_id"]) for c in uc.enumerate_cells() if c["parent_id"] == parent_id]
             if args.all_cells else [(args.regime, args.candidate)])
    worst = 0
    with tempfile.TemporaryDirectory(prefix="tile_family_harness_") as temp:
        workdir = args.workdir or Path(temp)
        workdir.mkdir(parents=True, exist_ok=True)
        for regime, cand in cells:
            try:
                result = run_candidate(parent_id, args.source_root, regime, cand, workdir)
            except RunnerBlocked as exc:
                print(str(exc), file=sys.stderr)
                worst = 3
                if not args.all_cells:
                    return 3
                continue
            print(json.dumps(result, sort_keys=True))
            if not result["correctness_check"]:
                worst = 3
    return worst
